# SPDX-License-Identifier: Apache-2.0
#
# Turns the stock FreeSWITCH image into this project's switch, at every boot.
#
# The image's own entrypoint unpacks the vanilla configuration into
# /etc/freeswitch the first time, then sources this file before starting
# FreeSWITCH. Everything here is therefore an overlay on vanilla, and is
# written to be idempotent: the configuration volume survives restarts, and a
# rebuilt image must still be able to change what it installs.
#
# It applies design 01 §7's diffs D1-D7 and the D8 deploy step, minus what
# vanilla already gets right (the A-law codec typo is local to the dev box).

# The image's entrypoint sources this file, so a bare `set -e` would change how
# the rest of that script behaves. The work happens in a subshell instead, and
# only its failure propagates — a half-configured switch must not start.
aicc_configure() (
set -e

# busybox here ships no `install`, and a missing command does not stop an ash
# subshell reliably — so copies go through cp and every one of them is checked
# at the end. A switch that silently kept the vanilla configuration would look
# healthy and answer nothing.
copy() { cp -f "$@" || { echo "aicc: cannot copy $*" >&2; exit 1; }; }

CONF=/etc/freeswitch
SCRIPTS=/usr/share/freeswitch/scripts
SRC=/aicc/src        # the repository's freeswitch/ directory
OVERLAY=/aicc/conf   # files this demo owns outright

echo "aicc: applying switch configuration"

# --- D8: the Lua scripts and the three configuration files we ship ----------
#
# dialplan/aicc.xml is a context of its own, not an include dropped into the
# stock ones: every account aicc_xml.lua serves is put in that context, so the
# whole of what an agent phone can dial lives in one file and the shipped
# dialplan is left alone (design 01 §7 D6, superseded).
mkdir -p "$SCRIPTS" "$CONF/sip_profiles/external" "$CONF/dialplan/public"
copy "$SRC"/scripts/*.lua "$SCRIPTS/"
copy "$SRC/conf/sip_profiles/external/aicc_bot.xml" "$CONF/sip_profiles/external/"
copy "$SRC/conf/dialplan/public/05_aicc.xml"        "$CONF/dialplan/public/"
copy "$SRC/conf/dialplan/aicc.xml"                  "$CONF/dialplan/"

# An older build of this image put a queue-extension include into the stock
# default context. It is part of the aicc context now, and a stale copy would
# keep answering 7xxx for anyone still routed through default.
rm -f "$CONF/dialplan/default/05_aicc.xml"

# --- D3: bind the XML handler that serves the directory and the queues ------
copy "$OVERLAY/autoload_configs/lua.conf.xml" "$CONF/autoload_configs/lua.conf.xml"

# --- the network list the event socket admits the application from ----------
copy "$OVERLAY/autoload_configs/acl.conf.xml" "$CONF/autoload_configs/acl.conf.xml"

# --- the event socket the application connects on ---------------------------
# Port 18021, not the stock 8021: the project documents that everywhere, and a
# switch that shares a host with another one should not fight over it.
sed -e "s|@ESL_PASSWORD@|${AICC_ESL_PASSWORD:-ClueCon}|" \
    "$OVERLAY/autoload_configs/event_socket.conf.xml" > "$CONF/autoload_configs/event_socket.conf.xml"

# --- D1: mod_callcenter is the queue engine, mod_pgsql reaches the database -
sed -i \
    -e 's|<!--[[:space:]]*<load module="mod_callcenter"/>[[:space:]]*-->|<load module="mod_callcenter"/>|' \
    "$CONF/autoload_configs/modules.conf.xml"
grep -q '<load module="mod_pgsql"/>' "$CONF/autoload_configs/modules.conf.xml" || sed -i \
    -e 's|<load module="mod_lua"/>|<load module="mod_lua"/>\n    <load module="mod_pgsql"/>|' \
    "$CONF/autoload_configs/modules.conf.xml"
for module in mod_callcenter mod_lua mod_pgsql; do
    grep -q "<load module=\"$module\"/>" "$CONF/autoload_configs/modules.conf.xml" || {
        echo "aicc: could not enable $module" >&2; exit 1
    }
done

# --- D7: room for the outbound ramp, and channel identifiers we can order ---
# uuid-version is a 1.11 parameter; on 1.10 it is simply ignored and channel
# UUIDs stay v4. Nothing depends on their ordering, only on their uniqueness.
sed -i \
    -e 's|<param name="sessions-per-second" value="[0-9]*"/>|<param name="sessions-per-second" value="100"/>|' \
    -e 's|<!--[[:space:]]*<param name="rtp-start-port" value="[0-9]*"/>[[:space:]]*-->|<param name="rtp-start-port" value="16384"/>|' \
    -e 's|<!--[[:space:]]*<param name="rtp-end-port" value="[0-9]*"/>[[:space:]]*-->|<param name="rtp-end-port" value="16584"/>|' \
    "$CONF/autoload_configs/switch.conf.xml"
grep -q 'uuid-version' "$CONF/autoload_configs/switch.conf.xml" || sed -i \
    -e 's|<param name="max-sessions"|<param name="uuid-version" value="7"/>\n    <param name="max-sessions"|' \
    "$CONF/autoload_configs/switch.conf.xml"

# --- the variables our scripts and the gateway read -------------------------
# Written as a separate file so vars.xml stays vanilla and a changed password
# never leaves a stale copy behind.
cat > "$CONF/vars_aicc.xml" <<XML
<!-- Generated by the demo entrypoint at every boot. Do not edit. -->
<include>
  <X-PRE-PROCESS cmd="set" data="domain=${AICC_DOMAIN:-aicc.demo}"/>
  <X-PRE-PROCESS cmd="set" data="domain_name=\$\${domain}"/>
  <X-PRE-PROCESS cmd="set" data="aicc_lua_dsn=pgsql://host=${AICC_DB_HOST:-postgres} dbname=aicc user=aicc_lua password='${AICC_LUA_PASSWORD:-aicc-lua}'"/>
  <X-PRE-PROCESS cmd="set" data="aicc_cc_dsn=pgsql://host=${AICC_DB_HOST:-postgres} dbname=aicc_fs user=aicc password='${AICC_DB_PASSWORD:-aicc}'"/>
  <X-PRE-PROCESS cmd="set" data="aicc_bot_host=${AICC_BOT_HOST:-aicc}"/>
  <X-PRE-PROCESS cmd="set" data="aicc_bot_port=${AICC_BOT_PORT:-6060}"/>
  <X-PRE-PROCESS cmd="set" data="aicc_recordings_dir=/var/lib/freeswitch/recordings"/>
XML
# Vanilla resolves the external addresses over STUN, which on a laptop
# advertises the internet-facing address of the whole network — and the bot
# leg, which rides the external profile, would then be told to send its media
# there. The container's own address is right for a self-contained demo; a
# phone outside this machine needs the host's, which is what AICC_EXTERNAL_IP
# is for.
external_ip="${AICC_EXTERNAL_IP:-\$\${local_ip_v4}}"
cat >> "$CONF/vars_aicc.xml" <<XML
  <X-PRE-PROCESS cmd="set" data="external_rtp_ip=$external_ip"/>
  <X-PRE-PROCESS cmd="set" data="external_sip_ip=$external_ip"/>
XML
echo '</include>' >> "$CONF/vars_aicc.xml"

# vars.xml is preprocessed before anything else, so ours has to be pulled in
# from inside it — last, so our values win, and only once however often this
# runs.
grep -q 'vars_aicc.xml' "$CONF/vars.xml" || sed -i \
    -e 's|</include>|  <X-PRE-PROCESS cmd="include" data="vars_aicc.xml"/>\n</include>|' \
    "$CONF/vars.xml"
grep -q 'vars_aicc.xml' "$CONF/vars.xml" || {
    echo "aicc: could not include vars_aicc.xml" >&2; exit 1
}

mkdir -p /var/lib/freeswitch/recordings
chown freeswitch:freeswitch /var/lib/freeswitch/recordings
chown -R freeswitch:freeswitch "$CONF"

# Nothing above may have quietly failed.
for expected in \
    "$SCRIPTS/aicc_xml.lua" \
    "$SCRIPTS/aicc_inbound.lua" \
    "$SCRIPTS/aicc_queue.lua" \
    "$CONF/sip_profiles/external/aicc_bot.xml" \
    "$CONF/dialplan/public/05_aicc.xml" \
    "$CONF/dialplan/aicc.xml" \
    "$CONF/vars_aicc.xml"; do
    [ -f "$expected" ] || { echo "aicc: $expected was not installed" >&2; exit 1; }
done
grep -q 'xml-handler-script' "$CONF/autoload_configs/lua.conf.xml" || {
    echo "aicc: the XML handler is not bound" >&2; exit 1
}

# --- Live transcription needs mod_audio_stream, and must not run without it -
#
# The stock image does not carry this module. A stack that comes up anyway is
# the worst outcome available: the application is healthy, the switch is
# healthy, calls connect, agents answer, and the transcript panel simply says
# "Connecting..." for ever. Nothing anywhere reports a fault, because from each
# component's own point of view there isn't one.
#
# So the guarantee here is not "the module is present" — that is a property of
# whatever built the image, and future images may drop it. The guarantee is
# that a stack configured to transcribe cannot start without it.
# The module directory differs between FreeSWITCH builds, so the standard two
# are searched and a differently-built image can name its own.
MOD_DIRS=${AICC_FS_MOD_DIR:-/usr/lib/freeswitch/mod /usr/local/freeswitch/mod}
AUDIO_STREAM_SO=""
for dir in $MOD_DIRS; do
    [ -f "$dir/mod_audio_stream.so" ] && { AUDIO_STREAM_SO="$dir/mod_audio_stream.so"; break; }
done

case "${AICC_TRANSCRIPTION_ENABLED:-false}" in
[Tt]rue|1|[Yy]es)
    [ -n "$AUDIO_STREAM_SO" ] || {
        cat >&2 <<'MISSING'
aicc: transcription is enabled but mod_audio_stream is not in this image.

Refusing to start. Without it the switch cannot tap an agent's leg, so the
stack would come up entirely healthy and transcribe nothing at all: the
application would be fine, the switch would be fine, calls would connect, and
the agent's transcript panel would say "Connecting..." until the call ended.

Either build the module into the image (see freeswitch/README.md, and run
freeswitch/assert-audio-stream.sh against the result — it must declare
libspeexdsp or it will tap at the wrong rate), or set
AICC_TRANSCRIPTION_ENABLED=false for a stack that honestly does not transcribe.
MISSING
        exit 1
    }
    grep -q '<load module="mod_audio_stream"/>' "$CONF/autoload_configs/modules.conf.xml" || sed -i \
        -e 's|<load module="mod_callcenter"/>|<load module="mod_callcenter"/>\n    <load module="mod_audio_stream"/>|' \
        "$CONF/autoload_configs/modules.conf.xml"
    grep -q '<load module="mod_audio_stream"/>' "$CONF/autoload_configs/modules.conf.xml" || {
        echo "aicc: could not enable mod_audio_stream" >&2; exit 1
    }
    echo "aicc: live transcription enabled, mod_audio_stream at $AUDIO_STREAM_SO"
    ;;
*)
    # Transcription off: say so once, so that a stack which is not
    # transcribing is never a surprise to whoever reads the log.
    echo "aicc: live transcription disabled (AICC_TRANSCRIPTION_ENABLED is not true)"
    ;;
esac

echo "aicc: switch configuration applied"
)

aicc_configure || exit 1
