// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agents.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const closeAgentStateLog = `-- name: CloseAgentStateLog :exec
UPDATE agent_state_logs
SET exited_at = $2
WHERE agent_id = $1 AND exited_at IS NULL
`

type CloseAgentStateLogParams struct {
	AgentID  uuid.UUID          `json:"agentId"`
	ExitedAt pgtype.Timestamptz `json:"exitedAt"`
}

func (q *Queries) CloseAgentStateLog(ctx context.Context, arg CloseAgentStateLogParams) error {
	_, err := q.db.Exec(ctx, closeAgentStateLog, arg.AgentID, arg.ExitedAt)
	return err
}

const createAgent = `-- name: CreateAgent :one

INSERT INTO agents (id, user_id, callcenter_name, is_auto_answer, default_extension_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, callcenter_name, is_auto_answer, default_extension_id, created_at
`

type CreateAgentParams struct {
	ID                 uuid.UUID  `json:"id"`
	UserID             uuid.UUID  `json:"userId"`
	CallcenterName     string     `json:"callcenterName"`
	IsAutoAnswer       bool       `json:"isAutoAnswer"`
	DefaultExtensionID *uuid.UUID `json:"defaultExtensionId"`
}

// SPDX-License-Identifier: Apache-2.0
func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, createAgent,
		arg.ID,
		arg.UserID,
		arg.CallcenterName,
		arg.IsAutoAnswer,
		arg.DefaultExtensionID,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CallcenterName,
		&i.IsAutoAnswer,
		&i.DefaultExtensionID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAgent = `-- name: DeleteAgent :exec
DELETE FROM agents WHERE id = $1
`

func (q *Queries) DeleteAgent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAgent, id)
	return err
}

const getAgent = `-- name: GetAgent :one
SELECT id, user_id, callcenter_name, is_auto_answer, default_extension_id, created_at FROM agents WHERE id = $1
`

func (q *Queries) GetAgent(ctx context.Context, id uuid.UUID) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgent, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CallcenterName,
		&i.IsAutoAnswer,
		&i.DefaultExtensionID,
		&i.CreatedAt,
	)
	return i, err
}

const getAgentByUserID = `-- name: GetAgentByUserID :one
SELECT id, user_id, callcenter_name, is_auto_answer, default_extension_id, created_at FROM agents WHERE user_id = $1
`

func (q *Queries) GetAgentByUserID(ctx context.Context, userID uuid.UUID) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgentByUserID, userID)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CallcenterName,
		&i.IsAutoAnswer,
		&i.DefaultExtensionID,
		&i.CreatedAt,
	)
	return i, err
}

const getAgentState = `-- name: GetAgentState :one
SELECT agent_id, state, reason, extension_number, entered_at, wrap_up_call_id FROM agent_states WHERE agent_id = $1
`

func (q *Queries) GetAgentState(ctx context.Context, agentID uuid.UUID) (AgentState, error) {
	row := q.db.QueryRow(ctx, getAgentState, agentID)
	var i AgentState
	err := row.Scan(
		&i.AgentID,
		&i.State,
		&i.Reason,
		&i.ExtensionNumber,
		&i.EnteredAt,
		&i.WrapUpCallID,
	)
	return i, err
}

const listAgentRoster = `-- name: ListAgentRoster :many
SELECT a.id AS agent_id,
       a.callcenter_name,
       a.is_auto_answer,
       a.default_extension_id,
       e.number AS default_extension_number,
       u.id AS user_id,
       u.username,
       u.display_name,
       u.status AS user_status,
       COALESCE(s.state, 'LOGGED_OUT') AS state,
       s.reason,
       s.extension_number,
       COALESCE(s.entered_at, a.created_at) AS entered_at,
       s.wrap_up_call_id
FROM agents a
JOIN users u ON u.id = a.user_id
LEFT JOIN agent_states s ON s.agent_id = a.id
LEFT JOIN extensions e ON e.id = a.default_extension_id
ORDER BY u.display_name
`

type ListAgentRosterRow struct {
	AgentID                uuid.UUID          `json:"agentId"`
	CallcenterName         string             `json:"callcenterName"`
	IsAutoAnswer           bool               `json:"isAutoAnswer"`
	DefaultExtensionID     *uuid.UUID         `json:"defaultExtensionId"`
	DefaultExtensionNumber *string            `json:"defaultExtensionNumber"`
	UserID                 uuid.UUID          `json:"userId"`
	Username               string             `json:"username"`
	DisplayName            string             `json:"displayName"`
	UserStatus             string             `json:"userStatus"`
	State                  string             `json:"state"`
	Reason                 *string            `json:"reason"`
	ExtensionNumber        *string            `json:"extensionNumber"`
	EnteredAt              pgtype.Timestamptz `json:"enteredAt"`
	WrapUpCallID           *uuid.UUID         `json:"wrapUpCallId"`
}

// The roster: one row per agent with everything a wallboard needs, so the
// derived availability can be computed without a second query.
func (q *Queries) ListAgentRoster(ctx context.Context) ([]ListAgentRosterRow, error) {
	rows, err := q.db.Query(ctx, listAgentRoster)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAgentRosterRow{}
	for rows.Next() {
		var i ListAgentRosterRow
		if err := rows.Scan(
			&i.AgentID,
			&i.CallcenterName,
			&i.IsAutoAnswer,
			&i.DefaultExtensionID,
			&i.DefaultExtensionNumber,
			&i.UserID,
			&i.Username,
			&i.DisplayName,
			&i.UserStatus,
			&i.State,
			&i.Reason,
			&i.ExtensionNumber,
			&i.EnteredAt,
			&i.WrapUpCallID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const openAgentStateLog = `-- name: OpenAgentStateLog :one
INSERT INTO agent_state_logs (agent_id, state, reason, entered_at)
VALUES ($1, $2, $3, $4)
RETURNING id, agent_id, state, reason, entered_at, exited_at
`

type OpenAgentStateLogParams struct {
	AgentID   uuid.UUID          `json:"agentId"`
	State     string             `json:"state"`
	Reason    *string            `json:"reason"`
	EnteredAt pgtype.Timestamptz `json:"enteredAt"`
}

func (q *Queries) OpenAgentStateLog(ctx context.Context, arg OpenAgentStateLogParams) (AgentStateLog, error) {
	row := q.db.QueryRow(ctx, openAgentStateLog,
		arg.AgentID,
		arg.State,
		arg.Reason,
		arg.EnteredAt,
	)
	var i AgentStateLog
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.State,
		&i.Reason,
		&i.EnteredAt,
		&i.ExitedAt,
	)
	return i, err
}

const updateAgent = `-- name: UpdateAgent :one
UPDATE agents
SET callcenter_name = $2, is_auto_answer = $3, default_extension_id = $4
WHERE id = $1
RETURNING id, user_id, callcenter_name, is_auto_answer, default_extension_id, created_at
`

type UpdateAgentParams struct {
	ID                 uuid.UUID  `json:"id"`
	CallcenterName     string     `json:"callcenterName"`
	IsAutoAnswer       bool       `json:"isAutoAnswer"`
	DefaultExtensionID *uuid.UUID `json:"defaultExtensionId"`
}

func (q *Queries) UpdateAgent(ctx context.Context, arg UpdateAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, updateAgent,
		arg.ID,
		arg.CallcenterName,
		arg.IsAutoAnswer,
		arg.DefaultExtensionID,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CallcenterName,
		&i.IsAutoAnswer,
		&i.DefaultExtensionID,
		&i.CreatedAt,
	)
	return i, err
}

const upsertAgentState = `-- name: UpsertAgentState :one
INSERT INTO agent_states (agent_id, state, reason, extension_number, entered_at, wrap_up_call_id)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (agent_id) DO UPDATE
SET state            = excluded.state,
    reason           = excluded.reason,
    extension_number = excluded.extension_number,
    entered_at       = excluded.entered_at,
    wrap_up_call_id  = excluded.wrap_up_call_id
RETURNING agent_id, state, reason, extension_number, entered_at, wrap_up_call_id
`

type UpsertAgentStateParams struct {
	AgentID         uuid.UUID          `json:"agentId"`
	State           string             `json:"state"`
	Reason          *string            `json:"reason"`
	ExtensionNumber *string            `json:"extensionNumber"`
	EnteredAt       pgtype.Timestamptz `json:"enteredAt"`
	WrapUpCallID    *uuid.UUID         `json:"wrapUpCallId"`
}

func (q *Queries) UpsertAgentState(ctx context.Context, arg UpsertAgentStateParams) (AgentState, error) {
	row := q.db.QueryRow(ctx, upsertAgentState,
		arg.AgentID,
		arg.State,
		arg.Reason,
		arg.ExtensionNumber,
		arg.EnteredAt,
		arg.WrapUpCallID,
	)
	var i AgentState
	err := row.Scan(
		&i.AgentID,
		&i.State,
		&i.Reason,
		&i.ExtensionNumber,
		&i.EnteredAt,
		&i.WrapUpCallID,
	)
	return i, err
}
