// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const createAPIKey = `-- name: CreateAPIKey :one

INSERT INTO api_keys (id, name, key_hash, key_prefix, scopes, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, key_hash, key_prefix, status, scopes, created_at, created_by, last_used_at, revoked_at
`

type CreateAPIKeyParams struct {
	ID        uuid.UUID  `json:"id"`
	Name      string     `json:"name"`
	KeyHash   []byte     `json:"keyHash"`
	KeyPrefix string     `json:"keyPrefix"`
	Scopes    []string   `json:"scopes"`
	CreatedBy *uuid.UUID `json:"createdBy"`
}

// SPDX-License-Identifier: Apache-2.0
func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.ID,
		arg.Name,
		arg.KeyHash,
		arg.KeyPrefix,
		arg.Scopes,
		arg.CreatedBy,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.Status,
		&i.Scopes,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAPIKey = `-- name: GetAPIKey :one
SELECT id, name, key_hash, key_prefix, status, scopes, created_at, created_by, last_used_at, revoked_at FROM api_keys WHERE id = $1
`

func (q *Queries) GetAPIKey(ctx context.Context, id uuid.UUID) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKey, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.Status,
		&i.Scopes,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, name, key_hash, key_prefix, status, scopes, created_at, created_by, last_used_at, revoked_at FROM api_keys WHERE key_hash = $1 AND status = 'ENABLED'
`

// The authentication lookup. By hash, directly — the same shape
// GetSessionByTokenHash uses, and for the same reason: the digest is the only
// thing both sides can compute, so there is nothing to scan and nothing to
// compare in application code.
//
// The status condition is inlined rather than checked by the caller so that a
// revoked key is not a row that came back and was then rejected: it does not
// come back. That is what makes REVOKED terminal at the only place it matters.
func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash []byte) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.Status,
		&i.Scopes,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, name, key_hash, key_prefix, status, scopes, created_at, created_by, last_used_at, revoked_at FROM api_keys ORDER BY created_at DESC
`

func (q *Queries) ListAPIKeys(ctx context.Context) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.KeyHash,
			&i.KeyPrefix,
			&i.Status,
			&i.Scopes,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :one
UPDATE api_keys
SET status = 'REVOKED', revoked_at = now()
WHERE id = $1 AND status = 'ENABLED'
RETURNING id, name, key_hash, key_prefix, status, scopes, created_at, created_by, last_used_at, revoked_at
`

// Revocation is terminal, and this is where that is true rather than in a
// comment: the WHERE clause matches only an enabled key, so revoking twice
// returns no row and the second caller is told the key is already revoked
// instead of quietly moving revoked_at.
func (q *Queries) RevokeAPIKey(ctx context.Context, id uuid.UUID) (ApiKey, error) {
	row := q.db.QueryRow(ctx, revokeAPIKey, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.Status,
		&i.Scopes,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const touchAPIKey = `-- name: TouchAPIKey :exec
UPDATE api_keys SET last_used_at = now() WHERE id = $1 AND status = 'ENABLED'
`

func (q *Queries) TouchAPIKey(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchAPIKey, id)
	return err
}

const updateAPIKey = `-- name: UpdateAPIKey :one
UPDATE api_keys
SET name   = coalesce($2, name),
    scopes = coalesce($3::text[], scopes)
WHERE id = $1
RETURNING id, name, key_hash, key_prefix, status, scopes, created_at, created_by, last_used_at, revoked_at
`

type UpdateAPIKeyParams struct {
	ID     uuid.UUID `json:"id"`
	Name   *string   `json:"name"`
	Scopes []string  `json:"scopes"`
}

func (q *Queries) UpdateAPIKey(ctx context.Context, arg UpdateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, updateAPIKey, arg.ID, arg.Name, arg.Scopes)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.Status,
		&i.Scopes,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}
