// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contacts.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countContacts = `-- name: CountContacts :one
SELECT count(*) FROM contacts c
WHERE ($1::text = '' OR c.phone_number = $1)
  AND ($2::text = ''
       OR c.phone_number ILIKE '%' || $2 || '%'
       OR c.name ILIKE '%' || $2 || '%'
       OR c.company ILIKE '%' || $2 || '%')
`

type CountContactsParams struct {
	PhoneNumber string `json:"phoneNumber"`
	Q           string `json:"q"`
}

func (q *Queries) CountContacts(ctx context.Context, arg CountContactsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countContacts, arg.PhoneNumber, arg.Q)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteContact = `-- name: DeleteContact :execrows
DELETE FROM contacts WHERE id = $1
`

func (q *Queries) DeleteContact(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteContact, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getContact = `-- name: GetContact :one
SELECT id, phone_number, name, company, email, tags, notes, created_at, updated_at, updated_by FROM contacts WHERE id = $1
`

func (q *Queries) GetContact(ctx context.Context, id uuid.UUID) (Contact, error) {
	row := q.db.QueryRow(ctx, getContact, id)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.Name,
		&i.Company,
		&i.Email,
		&i.Tags,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const insertContact = `-- name: InsertContact :one


INSERT INTO contacts (id, phone_number, name, company, email, tags, notes, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, phone_number, name, company, email, tags, notes, created_at, updated_at, updated_by
`

type InsertContactParams struct {
	ID          uuid.UUID  `json:"id"`
	PhoneNumber string     `json:"phoneNumber"`
	Name        string     `json:"name"`
	Company     string     `json:"company"`
	Email       string     `json:"email"`
	Tags        []string   `json:"tags"`
	Notes       string     `json:"notes"`
	UpdatedBy   *uuid.UUID `json:"updatedBy"`
}

// SPDX-License-Identifier: Apache-2.0
// Contacts are keyed by phone number: the cockpit's one question is "who is
// this number", and last_call_at is answered from the ledger by that number.
func (q *Queries) InsertContact(ctx context.Context, arg InsertContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, insertContact,
		arg.ID,
		arg.PhoneNumber,
		arg.Name,
		arg.Company,
		arg.Email,
		arg.Tags,
		arg.Notes,
		arg.UpdatedBy,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.Name,
		&i.Company,
		&i.Email,
		&i.Tags,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const listContacts = `-- name: ListContacts :many
SELECT c.id, c.phone_number, c.name, c.company, c.email, c.tags, c.notes, c.created_at, c.updated_at, c.updated_by,
       (SELECT max(started_at) FROM cdrs
         WHERE from_number = c.phone_number OR to_number = c.phone_number)::timestamptz AS last_call_at
FROM contacts c
WHERE ($1::text = '' OR c.phone_number = $1)
  AND ($2::text = ''
       OR c.phone_number ILIKE '%' || $2 || '%'
       OR c.name ILIKE '%' || $2 || '%'
       OR c.company ILIKE '%' || $2 || '%')
ORDER BY c.updated_at DESC
LIMIT $4 OFFSET $3
`

type ListContactsParams struct {
	PhoneNumber string `json:"phoneNumber"`
	Q           string `json:"q"`
	PageOffset  int32  `json:"pageOffset"`
	PageLimit   int32  `json:"pageLimit"`
}

type ListContactsRow struct {
	Contact    Contact            `json:"contact"`
	LastCallAt pgtype.Timestamptz `json:"lastCallAt"`
}

func (q *Queries) ListContacts(ctx context.Context, arg ListContactsParams) ([]ListContactsRow, error) {
	rows, err := q.db.Query(ctx, listContacts,
		arg.PhoneNumber,
		arg.Q,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContactsRow{}
	for rows.Next() {
		var i ListContactsRow
		if err := rows.Scan(
			&i.Contact.ID,
			&i.Contact.PhoneNumber,
			&i.Contact.Name,
			&i.Contact.Company,
			&i.Contact.Email,
			&i.Contact.Tags,
			&i.Contact.Notes,
			&i.Contact.CreatedAt,
			&i.Contact.UpdatedAt,
			&i.Contact.UpdatedBy,
			&i.LastCallAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContact = `-- name: UpdateContact :one
UPDATE contacts
SET phone_number = $2, name = $3, company = $4, email = $5, tags = $6, notes = $7,
    updated_by = $8, updated_at = now()
WHERE id = $1
RETURNING id, phone_number, name, company, email, tags, notes, created_at, updated_at, updated_by
`

type UpdateContactParams struct {
	ID          uuid.UUID  `json:"id"`
	PhoneNumber string     `json:"phoneNumber"`
	Name        string     `json:"name"`
	Company     string     `json:"company"`
	Email       string     `json:"email"`
	Tags        []string   `json:"tags"`
	Notes       string     `json:"notes"`
	UpdatedBy   *uuid.UUID `json:"updatedBy"`
}

func (q *Queries) UpdateContact(ctx context.Context, arg UpdateContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, updateContact,
		arg.ID,
		arg.PhoneNumber,
		arg.Name,
		arg.Company,
		arg.Email,
		arg.Tags,
		arg.Notes,
		arg.UpdatedBy,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.Name,
		&i.Company,
		&i.Email,
		&i.Tags,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
