// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package queries

import (
	"context"
)

// iteratorForInsertTranscript implements pgx.CopyFromSource.
type iteratorForInsertTranscript struct {
	rows                 []InsertTranscriptParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertTranscript) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertTranscript) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].CallID,
		r.rows[0].Seq,
		r.rows[0].OccurredAt,
		r.rows[0].Role,
		r.rows[0].Kind,
		r.rows[0].Content,
	}, nil
}

func (r iteratorForInsertTranscript) Err() error {
	return nil
}

func (q *Queries) InsertTranscript(ctx context.Context, arg []InsertTranscriptParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"transcripts"}, []string{"call_id", "seq", "occurred_at", "role", "kind", "content"}, &iteratorForInsertTranscript{rows: arg})
}
