// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: flows.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const createFlow = `-- name: CreateFlow :one
INSERT INTO flows (id, slug, name, draft_spec)
VALUES ($1, $2, $3, $4)
RETURNING id, slug, name, draft_spec, published_revision_id, published_at, created_at, updated_at
`

type CreateFlowParams struct {
	ID        uuid.UUID `json:"id"`
	Slug      string    `json:"slug"`
	Name      string    `json:"name"`
	DraftSpec []byte    `json:"draftSpec"`
}

func (q *Queries) CreateFlow(ctx context.Context, arg CreateFlowParams) (Flow, error) {
	row := q.db.QueryRow(ctx, createFlow,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.DraftSpec,
	)
	var i Flow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.DraftSpec,
		&i.PublishedRevisionID,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createFlowRevision = `-- name: CreateFlowRevision :one
INSERT INTO flow_revisions (id, flow_id, spec, note)
VALUES ($1, $2, $3, $4)
RETURNING id, flow_id, spec, note, created_at
`

type CreateFlowRevisionParams struct {
	ID     uuid.UUID `json:"id"`
	FlowID uuid.UUID `json:"flowId"`
	Spec   []byte    `json:"spec"`
	Note   string    `json:"note"`
}

func (q *Queries) CreateFlowRevision(ctx context.Context, arg CreateFlowRevisionParams) (FlowRevision, error) {
	row := q.db.QueryRow(ctx, createFlowRevision,
		arg.ID,
		arg.FlowID,
		arg.Spec,
		arg.Note,
	)
	var i FlowRevision
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.Spec,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFlow = `-- name: DeleteFlow :exec
DELETE FROM flows WHERE id = $1
`

func (q *Queries) DeleteFlow(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteFlow, id)
	return err
}

const getFlow = `-- name: GetFlow :one
SELECT id, slug, name, draft_spec, published_revision_id, published_at, created_at, updated_at FROM flows WHERE id = $1
`

func (q *Queries) GetFlow(ctx context.Context, id uuid.UUID) (Flow, error) {
	row := q.db.QueryRow(ctx, getFlow, id)
	var i Flow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.DraftSpec,
		&i.PublishedRevisionID,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFlowBySlug = `-- name: GetFlowBySlug :one
SELECT id, slug, name, draft_spec, published_revision_id, published_at, created_at, updated_at FROM flows WHERE slug = $1
`

func (q *Queries) GetFlowBySlug(ctx context.Context, slug string) (Flow, error) {
	row := q.db.QueryRow(ctx, getFlowBySlug, slug)
	var i Flow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.DraftSpec,
		&i.PublishedRevisionID,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublishedSpec = `-- name: GetPublishedSpec :one
SELECT r.spec
FROM flows f
JOIN flow_revisions r ON r.id = f.published_revision_id
WHERE f.id = $1
`

func (q *Queries) GetPublishedSpec(ctx context.Context, id uuid.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getPublishedSpec, id)
	var spec []byte
	err := row.Scan(&spec)
	return spec, err
}

const listFlows = `-- name: ListFlows :many

SELECT id, slug, name, draft_spec, published_revision_id, published_at, created_at, updated_at FROM flows ORDER BY name
`

// SPDX-License-Identifier: Apache-2.0
func (q *Queries) ListFlows(ctx context.Context) ([]Flow, error) {
	rows, err := q.db.Query(ctx, listFlows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Flow{}
	for rows.Next() {
		var i Flow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.DraftSpec,
			&i.PublishedRevisionID,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPublishedRevision = `-- name: SetPublishedRevision :exec
UPDATE flows
SET published_revision_id = $2, published_at = now(), updated_at = now()
WHERE id = $1
`

type SetPublishedRevisionParams struct {
	ID                  uuid.UUID  `json:"id"`
	PublishedRevisionID *uuid.UUID `json:"publishedRevisionId"`
}

func (q *Queries) SetPublishedRevision(ctx context.Context, arg SetPublishedRevisionParams) error {
	_, err := q.db.Exec(ctx, setPublishedRevision, arg.ID, arg.PublishedRevisionID)
	return err
}

const updateFlowDraft = `-- name: UpdateFlowDraft :one
UPDATE flows
SET name = $2, draft_spec = $3, updated_at = now()
WHERE id = $1
RETURNING id, slug, name, draft_spec, published_revision_id, published_at, created_at, updated_at
`

type UpdateFlowDraftParams struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	DraftSpec []byte    `json:"draftSpec"`
}

func (q *Queries) UpdateFlowDraft(ctx context.Context, arg UpdateFlowDraftParams) (Flow, error) {
	row := q.db.QueryRow(ctx, updateFlowDraft, arg.ID, arg.Name, arg.DraftSpec)
	var i Flow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.DraftSpec,
		&i.PublishedRevisionID,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
