// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ledger.sql

package queries

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimCallback = `-- name: ClaimCallback :one
UPDATE callbacks
SET status = 'CLAIMED', handled_by = $2
WHERE id = $1 AND status = 'OPEN'
RETURNING id, call_id, queue_id, phone_number, message, status, created_at, handled_by, handled_at, last_attempt_call_id, last_attempt_at, last_attempt_status
`

type ClaimCallbackParams struct {
	ID        uuid.UUID  `json:"id"`
	HandledBy *uuid.UUID `json:"handledBy"`
}

func (q *Queries) ClaimCallback(ctx context.Context, arg ClaimCallbackParams) (Callback, error) {
	row := q.db.QueryRow(ctx, claimCallback, arg.ID, arg.HandledBy)
	var i Callback
	err := row.Scan(
		&i.ID,
		&i.CallID,
		&i.QueueID,
		&i.PhoneNumber,
		&i.Message,
		&i.Status,
		&i.CreatedAt,
		&i.HandledBy,
		&i.HandledAt,
		&i.LastAttemptCallID,
		&i.LastAttemptAt,
		&i.LastAttemptStatus,
	)
	return i, err
}

const countAuditLogs = `-- name: CountAuditLogs :one
SELECT count(*) FROM audit_logs a
WHERE ($1::uuid IS NULL OR a.actor_id = $1::uuid)
  AND ($2::text IS NULL
       OR a.action LIKE $2::text || '%')
  AND ($3::timestamptz IS NULL OR a.occurred_at >= $3::timestamptz)
  AND ($4::timestamptz IS NULL OR a.occurred_at < $4::timestamptz)
`

type CountAuditLogsParams struct {
	ActorID      *uuid.UUID         `json:"actorId"`
	ActionPrefix *string            `json:"actionPrefix"`
	FromAt       pgtype.Timestamptz `json:"fromAt"`
	ToAt         pgtype.Timestamptz `json:"toAt"`
}

func (q *Queries) CountAuditLogs(ctx context.Context, arg CountAuditLogsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogs,
		arg.ActorID,
		arg.ActionPrefix,
		arg.FromAt,
		arg.ToAt,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCDRs = `-- name: CountCDRs :one
SELECT count(*) FROM cdrs
WHERE ($1::timestamptz IS NULL OR started_at >= $1)
  AND ($2::timestamptz IS NULL OR started_at < $2)
  AND ($3::uuid IS NULL OR queue_id = $3)
  AND ($4::uuid IS NULL OR primary_agent_id = $4
       OR $4 = ANY (agent_ids))
  AND ($5::text = '' OR status = $5)
  AND ($6::text = '' OR did = $6)
  AND ($7::text = '' OR from_number LIKE '%' || $7 || '%')
`

type CountCDRsParams struct {
	FromAt     pgtype.Timestamptz `json:"fromAt"`
	ToAt       pgtype.Timestamptz `json:"toAt"`
	QueueID    *uuid.UUID         `json:"queueId"`
	AgentID    *uuid.UUID         `json:"agentId"`
	Status     string             `json:"status"`
	Did        string             `json:"did"`
	FromNumber string             `json:"fromNumber"`
}

func (q *Queries) CountCDRs(ctx context.Context, arg CountCDRsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCDRs,
		arg.FromAt,
		arg.ToAt,
		arg.QueueID,
		arg.AgentID,
		arg.Status,
		arg.Did,
		arg.FromNumber,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const expiredRecordings = `-- name: ExpiredRecordings :many

SELECT id, call_id, backend, bucket, object_key, size_bytes, duration_sec, format, created_at, deleted_at FROM recordings
WHERE deleted_at IS NULL
  AND created_at < now() - make_interval(days => $1::int)
ORDER BY created_at
LIMIT $2::int
`

type ExpiredRecordingsParams struct {
	RetentionDays int32 `json:"retentionDays"`
	MaxRows       int32 `json:"maxRows"`
}

// Recordings past their retention period, oldest first.
//
// Age is measured from when the recording was made, not from the call's start:
// they are the same instant in every real case, and created_at is the column
// this table actually has an answer for.
//
// Already-swept rows are excluded, so a sweep that fails halfway resumes
// rather than reconsidering what it has already deleted.
func (q *Queries) ExpiredRecordings(ctx context.Context, arg ExpiredRecordingsParams) ([]Recording, error) {
	rows, err := q.db.Query(ctx, expiredRecordings, arg.RetentionDays, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Recording{}
	for rows.Next() {
		var i Recording
		if err := rows.Scan(
			&i.ID,
			&i.CallID,
			&i.Backend,
			&i.Bucket,
			&i.ObjectKey,
			&i.SizeBytes,
			&i.DurationSec,
			&i.Format,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCDR = `-- name: GetCDR :one
SELECT call_id, started_at, answered_at, ended_at, call_type, language, from_number, to_number, did, flow_id, queue_id, agent_ids, primary_agent_id, ring_sec, bot_sec, queue_wait_sec, talk_sec, total_sec, status, hangup_cause, missed_reason, disposition, is_contained, has_recording, user_data, tech, legs, bill_sec FROM cdrs WHERE call_id = $1
`

func (q *Queries) GetCDR(ctx context.Context, callID uuid.UUID) (Cdr, error) {
	row := q.db.QueryRow(ctx, getCDR, callID)
	var i Cdr
	err := row.Scan(
		&i.CallID,
		&i.StartedAt,
		&i.AnsweredAt,
		&i.EndedAt,
		&i.CallType,
		&i.Language,
		&i.FromNumber,
		&i.ToNumber,
		&i.Did,
		&i.FlowID,
		&i.QueueID,
		&i.AgentIds,
		&i.PrimaryAgentID,
		&i.RingSec,
		&i.BotSec,
		&i.QueueWaitSec,
		&i.TalkSec,
		&i.TotalSec,
		&i.Status,
		&i.HangupCause,
		&i.MissedReason,
		&i.Disposition,
		&i.IsContained,
		&i.HasRecording,
		&i.UserData,
		&i.Tech,
		&i.Legs,
		&i.BillSec,
	)
	return i, err
}

const getDisposition = `-- name: GetDisposition :one
SELECT code, label FROM dispositions WHERE code = $1 AND is_enabled
`

type GetDispositionRow struct {
	Code  string `json:"code"`
	Label string `json:"label"`
}

func (q *Queries) GetDisposition(ctx context.Context, code string) (GetDispositionRow, error) {
	row := q.db.QueryRow(ctx, getDisposition, code)
	var i GetDispositionRow
	err := row.Scan(&i.Code, &i.Label)
	return i, err
}

const getRecording = `-- name: GetRecording :one
SELECT id, call_id, backend, bucket, object_key, size_bytes, duration_sec, format, created_at, deleted_at FROM recordings WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetRecording(ctx context.Context, id uuid.UUID) (Recording, error) {
	row := q.db.QueryRow(ctx, getRecording, id)
	var i Recording
	err := row.Scan(
		&i.ID,
		&i.CallID,
		&i.Backend,
		&i.Bucket,
		&i.ObjectKey,
		&i.SizeBytes,
		&i.DurationSec,
		&i.Format,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getWrapUp = `-- name: GetWrapUp :one
SELECT call_id, agent_id, disposition_code, disposition_label, note, created_at, is_confirmed FROM wrap_ups WHERE call_id = $1 AND agent_id = $2
`

type GetWrapUpParams struct {
	CallID  uuid.UUID `json:"callId"`
	AgentID uuid.UUID `json:"agentId"`
}

func (q *Queries) GetWrapUp(ctx context.Context, arg GetWrapUpParams) (WrapUp, error) {
	row := q.db.QueryRow(ctx, getWrapUp, arg.CallID, arg.AgentID)
	var i WrapUp
	err := row.Scan(
		&i.CallID,
		&i.AgentID,
		&i.DispositionCode,
		&i.DispositionLabel,
		&i.Note,
		&i.CreatedAt,
		&i.IsConfirmed,
	)
	return i, err
}

const handleCallback = `-- name: HandleCallback :one
UPDATE callbacks
SET status = $2, handled_by = $3, handled_at = now()
WHERE id = $1
RETURNING id, call_id, queue_id, phone_number, message, status, created_at, handled_by, handled_at, last_attempt_call_id, last_attempt_at, last_attempt_status
`

type HandleCallbackParams struct {
	ID        uuid.UUID  `json:"id"`
	Status    string     `json:"status"`
	HandledBy *uuid.UUID `json:"handledBy"`
}

func (q *Queries) HandleCallback(ctx context.Context, arg HandleCallbackParams) (Callback, error) {
	row := q.db.QueryRow(ctx, handleCallback, arg.ID, arg.Status, arg.HandledBy)
	var i Callback
	err := row.Scan(
		&i.ID,
		&i.CallID,
		&i.QueueID,
		&i.PhoneNumber,
		&i.Message,
		&i.Status,
		&i.CreatedAt,
		&i.HandledBy,
		&i.HandledAt,
		&i.LastAttemptCallID,
		&i.LastAttemptAt,
		&i.LastAttemptStatus,
	)
	return i, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_logs (actor_id, action, target_kind, target_id, detail, ip)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertAuditLogParams struct {
	ActorID    *uuid.UUID  `json:"actorId"`
	Action     string      `json:"action"`
	TargetKind string      `json:"targetKind"`
	TargetID   string      `json:"targetId"`
	Detail     []byte      `json:"detail"`
	IP         *netip.Addr `json:"ip"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.ActorID,
		arg.Action,
		arg.TargetKind,
		arg.TargetID,
		arg.Detail,
		arg.IP,
	)
	return err
}

const insertCDR = `-- name: InsertCDR :execrows

INSERT INTO cdrs (
    call_id, started_at, answered_at, ended_at, call_type, language,
    from_number, to_number, did, flow_id, queue_id,
    agent_ids, primary_agent_id,
    ring_sec, bot_sec, queue_wait_sec, talk_sec, bill_sec, total_sec,
    status, hangup_cause, missed_reason, disposition,
    is_contained, has_recording, user_data, tech, legs
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11,
    $12, $13,
    $14, $15, $16, $17, $18, $19,
    $20, $21, $22, $23,
    $24, $25, $26, $27, $28
) ON CONFLICT (call_id) DO UPDATE SET
    started_at = EXCLUDED.started_at,
    answered_at = EXCLUDED.answered_at,
    ended_at = EXCLUDED.ended_at,
    call_type = EXCLUDED.call_type,
    language = EXCLUDED.language,
    from_number = EXCLUDED.from_number,
    to_number = EXCLUDED.to_number,
    did = EXCLUDED.did,
    flow_id = EXCLUDED.flow_id,
    queue_id = EXCLUDED.queue_id,
    agent_ids = EXCLUDED.agent_ids,
    primary_agent_id = EXCLUDED.primary_agent_id,
    ring_sec = EXCLUDED.ring_sec,
    bot_sec = EXCLUDED.bot_sec,
    queue_wait_sec = EXCLUDED.queue_wait_sec,
    talk_sec = EXCLUDED.talk_sec,
    bill_sec = EXCLUDED.bill_sec,
    total_sec = EXCLUDED.total_sec,
    status = EXCLUDED.status,
    hangup_cause = EXCLUDED.hangup_cause,
    missed_reason = EXCLUDED.missed_reason,
    disposition = EXCLUDED.disposition,
    is_contained = EXCLUDED.is_contained,
    has_recording = EXCLUDED.has_recording,
    user_data = EXCLUDED.user_data,
    tech = EXCLUDED.tech,
    legs = EXCLUDED.legs
WHERE EXCLUDED.ended_at > cdrs.ended_at
`

type InsertCDRParams struct {
	CallID         uuid.UUID          `json:"callId"`
	StartedAt      pgtype.Timestamptz `json:"startedAt"`
	AnsweredAt     pgtype.Timestamptz `json:"answeredAt"`
	EndedAt        pgtype.Timestamptz `json:"endedAt"`
	CallType       string             `json:"callType"`
	Language       string             `json:"language"`
	FromNumber     string             `json:"fromNumber"`
	ToNumber       string             `json:"toNumber"`
	Did            string             `json:"did"`
	FlowID         *uuid.UUID         `json:"flowId"`
	QueueID        *uuid.UUID         `json:"queueId"`
	AgentIds       []uuid.UUID        `json:"agentIds"`
	PrimaryAgentID *uuid.UUID         `json:"primaryAgentId"`
	RingSec        int32              `json:"ringSec"`
	BotSec         int32              `json:"botSec"`
	QueueWaitSec   int32              `json:"queueWaitSec"`
	TalkSec        int32              `json:"talkSec"`
	BillSec        int32              `json:"billSec"`
	TotalSec       int32              `json:"totalSec"`
	Status         string             `json:"status"`
	HangupCause    string             `json:"hangupCause"`
	MissedReason   *string            `json:"missedReason"`
	Disposition    string             `json:"disposition"`
	IsContained    bool               `json:"isContained"`
	HasRecording   bool               `json:"hasRecording"`
	UserData       []byte             `json:"userData"`
	Tech           []byte             `json:"tech"`
	Legs           []byte             `json:"legs"`
}

// SPDX-License-Identifier: Apache-2.0
//
// One row per call, written by whichever path saw the call end — and, where
// both did, by the one that saw more of it.
//
// The two paths do not normally overlap: a transferred call belongs to the
// human path and a contained one to the bot's, and each declines to write the
// other's. They overlapped in exactly one situation, and it took a live
// restart to find: the bot's leg dies with the process, no transfer was ever
// marked, so the bot writes the call off as ended — and then the caller lives
// on, reaches a queue, and talks to somebody for four minutes that DO NOTHING
// silently discarded. The row said a bot call ended at the restart, with no
// agent, no queue and no talk time, on the record the carrier is billed from.
//
// A later ending means more of the call is known, so that row wins. The rule
// is monotone, which is what keeps this safe as an upsert: a row can only ever
// be replaced by one that reaches further, never flip back.
//
// :execrows rather than :exec, because the caller has to know whether the
// ledger actually changed. A webhook delivery is queued off the back of this
// (design 09 §2), and queueing one for a write that changed nothing would post
// the customer a duplicate of a CDR they already hold. Zero rows is the
// conflict clause declining; one is a real insert or a real replacement.
func (q *Queries) InsertCDR(ctx context.Context, arg InsertCDRParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertCDR,
		arg.CallID,
		arg.StartedAt,
		arg.AnsweredAt,
		arg.EndedAt,
		arg.CallType,
		arg.Language,
		arg.FromNumber,
		arg.ToNumber,
		arg.Did,
		arg.FlowID,
		arg.QueueID,
		arg.AgentIds,
		arg.PrimaryAgentID,
		arg.RingSec,
		arg.BotSec,
		arg.QueueWaitSec,
		arg.TalkSec,
		arg.BillSec,
		arg.TotalSec,
		arg.Status,
		arg.HangupCause,
		arg.MissedReason,
		arg.Disposition,
		arg.IsContained,
		arg.HasRecording,
		arg.UserData,
		arg.Tech,
		arg.Legs,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertCallback = `-- name: InsertCallback :one
INSERT INTO callbacks (id, call_id, queue_id, phone_number, message)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, call_id, queue_id, phone_number, message, status, created_at, handled_by, handled_at, last_attempt_call_id, last_attempt_at, last_attempt_status
`

type InsertCallbackParams struct {
	ID          uuid.UUID  `json:"id"`
	CallID      *uuid.UUID `json:"callId"`
	QueueID     *uuid.UUID `json:"queueId"`
	PhoneNumber string     `json:"phoneNumber"`
	Message     string     `json:"message"`
}

func (q *Queries) InsertCallback(ctx context.Context, arg InsertCallbackParams) (Callback, error) {
	row := q.db.QueryRow(ctx, insertCallback,
		arg.ID,
		arg.CallID,
		arg.QueueID,
		arg.PhoneNumber,
		arg.Message,
	)
	var i Callback
	err := row.Scan(
		&i.ID,
		&i.CallID,
		&i.QueueID,
		&i.PhoneNumber,
		&i.Message,
		&i.Status,
		&i.CreatedAt,
		&i.HandledBy,
		&i.HandledAt,
		&i.LastAttemptCallID,
		&i.LastAttemptAt,
		&i.LastAttemptStatus,
	)
	return i, err
}

const insertQualityReview = `-- name: InsertQualityReview :one
INSERT INTO quality_reviews (id, recording_id, call_id, reviewer_id, scores, total_score, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, recording_id, call_id, reviewer_id, scores, total_score, notes, created_at
`

type InsertQualityReviewParams struct {
	ID          uuid.UUID `json:"id"`
	RecordingID uuid.UUID `json:"recordingId"`
	CallID      uuid.UUID `json:"callId"`
	ReviewerID  uuid.UUID `json:"reviewerId"`
	Scores      []byte    `json:"scores"`
	TotalScore  int16     `json:"totalScore"`
	Notes       string    `json:"notes"`
}

func (q *Queries) InsertQualityReview(ctx context.Context, arg InsertQualityReviewParams) (QualityReview, error) {
	row := q.db.QueryRow(ctx, insertQualityReview,
		arg.ID,
		arg.RecordingID,
		arg.CallID,
		arg.ReviewerID,
		arg.Scores,
		arg.TotalScore,
		arg.Notes,
	)
	var i QualityReview
	err := row.Scan(
		&i.ID,
		&i.RecordingID,
		&i.CallID,
		&i.ReviewerID,
		&i.Scores,
		&i.TotalScore,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const insertQueueEvent = `-- name: InsertQueueEvent :exec
INSERT INTO queue_events (occurred_at, call_id, queue_id, event, agent_id, wait_ms)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertQueueEventParams struct {
	OccurredAt pgtype.Timestamptz `json:"occurredAt"`
	CallID     *uuid.UUID         `json:"callId"`
	QueueID    uuid.UUID          `json:"queueId"`
	Event      string             `json:"event"`
	AgentID    *uuid.UUID         `json:"agentId"`
	WaitMs     int32              `json:"waitMs"`
}

func (q *Queries) InsertQueueEvent(ctx context.Context, arg InsertQueueEventParams) error {
	_, err := q.db.Exec(ctx, insertQueueEvent,
		arg.OccurredAt,
		arg.CallID,
		arg.QueueID,
		arg.Event,
		arg.AgentID,
		arg.WaitMs,
	)
	return err
}

const insertRecording = `-- name: InsertRecording :one
INSERT INTO recordings (id, call_id, backend, bucket, object_key, size_bytes, duration_sec, format)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, call_id, backend, bucket, object_key, size_bytes, duration_sec, format, created_at, deleted_at
`

type InsertRecordingParams struct {
	ID          uuid.UUID `json:"id"`
	CallID      uuid.UUID `json:"callId"`
	Backend     string    `json:"backend"`
	Bucket      string    `json:"bucket"`
	ObjectKey   string    `json:"objectKey"`
	SizeBytes   int64     `json:"sizeBytes"`
	DurationSec int32     `json:"durationSec"`
	Format      string    `json:"format"`
}

func (q *Queries) InsertRecording(ctx context.Context, arg InsertRecordingParams) (Recording, error) {
	row := q.db.QueryRow(ctx, insertRecording,
		arg.ID,
		arg.CallID,
		arg.Backend,
		arg.Bucket,
		arg.ObjectKey,
		arg.SizeBytes,
		arg.DurationSec,
		arg.Format,
	)
	var i Recording
	err := row.Scan(
		&i.ID,
		&i.CallID,
		&i.Backend,
		&i.Bucket,
		&i.ObjectKey,
		&i.SizeBytes,
		&i.DurationSec,
		&i.Format,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertTranscriptLine = `-- name: InsertTranscriptLine :exec
INSERT INTO transcripts (call_id, seq, occurred_at, speaker, kind, content,
                         party_id, agent_id, offset_ms, language, source, provider, utterance_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
ON CONFLICT DO NOTHING
`

type InsertTranscriptLineParams struct {
	CallID      uuid.UUID          `json:"callId"`
	Seq         int32              `json:"seq"`
	OccurredAt  pgtype.Timestamptz `json:"occurredAt"`
	Speaker     string             `json:"speaker"`
	Kind        string             `json:"kind"`
	Content     []byte             `json:"content"`
	PartyID     *uuid.UUID         `json:"partyId"`
	AgentID     *uuid.UUID         `json:"agentId"`
	OffsetMs    int32              `json:"offsetMs"`
	Language    string             `json:"language"`
	Source      string             `json:"source"`
	Provider    string             `json:"provider"`
	UtteranceID string             `json:"utteranceId"`
}

// InsertTranscriptLine writes one line as it is spoken. The conflict target is
// the partial idempotency index, so a redelivered final is dropped rather than
// duplicated; DO NOTHING is correct because a final is never revised (D3).
func (q *Queries) InsertTranscriptLine(ctx context.Context, arg InsertTranscriptLineParams) error {
	_, err := q.db.Exec(ctx, insertTranscriptLine,
		arg.CallID,
		arg.Seq,
		arg.OccurredAt,
		arg.Speaker,
		arg.Kind,
		arg.Content,
		arg.PartyID,
		arg.AgentID,
		arg.OffsetMs,
		arg.Language,
		arg.Source,
		arg.Provider,
		arg.UtteranceID,
	)
	return err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT a.id, a.occurred_at, a.actor_id, COALESCE(u.username, '')::text AS actor_username,
       a.action, a.target_kind, a.target_id, a.detail, a.ip
FROM audit_logs a
LEFT JOIN users u ON u.id = a.actor_id
WHERE ($3::uuid IS NULL OR a.actor_id = $3::uuid)
  AND ($4::text IS NULL
       OR a.action LIKE $4::text || '%')
  AND ($5::timestamptz IS NULL OR a.occurred_at >= $5::timestamptz)
  AND ($6::timestamptz IS NULL OR a.occurred_at < $6::timestamptz)
ORDER BY a.occurred_at DESC, a.id DESC
LIMIT $1 OFFSET $2
`

type ListAuditLogsParams struct {
	Limit        int32              `json:"limit"`
	Offset       int32              `json:"offset"`
	ActorID      *uuid.UUID         `json:"actorId"`
	ActionPrefix *string            `json:"actionPrefix"`
	FromAt       pgtype.Timestamptz `json:"fromAt"`
	ToAt         pgtype.Timestamptz `json:"toAt"`
}

type ListAuditLogsRow struct {
	ID            int64              `json:"id"`
	OccurredAt    pgtype.Timestamptz `json:"occurredAt"`
	ActorID       *uuid.UUID         `json:"actorId"`
	ActorUsername string             `json:"actorUsername"`
	Action        string             `json:"action"`
	TargetKind    string             `json:"targetKind"`
	TargetID      string             `json:"targetId"`
	Detail        []byte             `json:"detail"`
	IP            *netip.Addr        `json:"ip"`
}

// Newest first, with the actor's name resolved at read time. LEFT JOIN because
// an account can be deleted while its actions stay recorded — the row keeps the
// id either way, so a cleaned-up roster does not erase what its accounts did.
// COALESCE, not a bare cast: the join's NULL is the ordinary case for a deleted
// account, and empty is what the reader turns back into "no name to show".
func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]ListAuditLogsRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogs,
		arg.Limit,
		arg.Offset,
		arg.ActorID,
		arg.ActionPrefix,
		arg.FromAt,
		arg.ToAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogsRow{}
	for rows.Next() {
		var i ListAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.ActorID,
			&i.ActorUsername,
			&i.Action,
			&i.TargetKind,
			&i.TargetID,
			&i.Detail,
			&i.IP,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCDRs = `-- name: ListCDRs :many
SELECT call_id, started_at, answered_at, ended_at, call_type, language, from_number, to_number, did, flow_id, queue_id, agent_ids, primary_agent_id, ring_sec, bot_sec, queue_wait_sec, talk_sec, total_sec, status, hangup_cause, missed_reason, disposition, is_contained, has_recording, user_data, tech, legs, bill_sec FROM cdrs
WHERE ($1::timestamptz IS NULL OR started_at >= $1)
  AND ($2::timestamptz IS NULL OR started_at < $2)
  AND ($3::uuid IS NULL OR queue_id = $3)
  AND ($4::uuid IS NULL OR primary_agent_id = $4
       OR $4 = ANY (agent_ids))
  AND ($5::text = '' OR status = $5)
  AND ($6::text = '' OR did = $6)
  AND ($7::text = '' OR from_number LIKE '%' || $7 || '%')
ORDER BY started_at DESC
LIMIT $9 OFFSET $8
`

type ListCDRsParams struct {
	FromAt     pgtype.Timestamptz `json:"fromAt"`
	ToAt       pgtype.Timestamptz `json:"toAt"`
	QueueID    *uuid.UUID         `json:"queueId"`
	AgentID    *uuid.UUID         `json:"agentId"`
	Status     string             `json:"status"`
	Did        string             `json:"did"`
	FromNumber string             `json:"fromNumber"`
	PageOffset int32              `json:"pageOffset"`
	PageLimit  int32              `json:"pageLimit"`
}

func (q *Queries) ListCDRs(ctx context.Context, arg ListCDRsParams) ([]Cdr, error) {
	rows, err := q.db.Query(ctx, listCDRs,
		arg.FromAt,
		arg.ToAt,
		arg.QueueID,
		arg.AgentID,
		arg.Status,
		arg.Did,
		arg.FromNumber,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Cdr{}
	for rows.Next() {
		var i Cdr
		if err := rows.Scan(
			&i.CallID,
			&i.StartedAt,
			&i.AnsweredAt,
			&i.EndedAt,
			&i.CallType,
			&i.Language,
			&i.FromNumber,
			&i.ToNumber,
			&i.Did,
			&i.FlowID,
			&i.QueueID,
			&i.AgentIds,
			&i.PrimaryAgentID,
			&i.RingSec,
			&i.BotSec,
			&i.QueueWaitSec,
			&i.TalkSec,
			&i.TotalSec,
			&i.Status,
			&i.HangupCause,
			&i.MissedReason,
			&i.Disposition,
			&i.IsContained,
			&i.HasRecording,
			&i.UserData,
			&i.Tech,
			&i.Legs,
			&i.BillSec,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCallbacks = `-- name: ListCallbacks :many
SELECT id, call_id, queue_id, phone_number, message, status, created_at, handled_by, handled_at, last_attempt_call_id, last_attempt_at, last_attempt_status FROM callbacks
WHERE ($1::text = '' OR status = $1)
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListCallbacksParams struct {
	Status     string `json:"status"`
	PageOffset int32  `json:"pageOffset"`
	PageLimit  int32  `json:"pageLimit"`
}

func (q *Queries) ListCallbacks(ctx context.Context, arg ListCallbacksParams) ([]Callback, error) {
	rows, err := q.db.Query(ctx, listCallbacks, arg.Status, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Callback{}
	for rows.Next() {
		var i Callback
		if err := rows.Scan(
			&i.ID,
			&i.CallID,
			&i.QueueID,
			&i.PhoneNumber,
			&i.Message,
			&i.Status,
			&i.CreatedAt,
			&i.HandledBy,
			&i.HandledAt,
			&i.LastAttemptCallID,
			&i.LastAttemptAt,
			&i.LastAttemptStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledDispositions = `-- name: ListEnabledDispositions :many

SELECT code, label, position, is_enabled FROM dispositions WHERE is_enabled ORDER BY position, code
`

// After-call work: the vocabulary, and what agents file against calls.
func (q *Queries) ListEnabledDispositions(ctx context.Context) ([]Disposition, error) {
	rows, err := q.db.Query(ctx, listEnabledDispositions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Disposition{}
	for rows.Next() {
		var i Disposition
		if err := rows.Scan(
			&i.Code,
			&i.Label,
			&i.Position,
			&i.IsEnabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQualityReviewsByCall = `-- name: ListQualityReviewsByCall :many
SELECT id, recording_id, call_id, reviewer_id, scores, total_score, notes, created_at FROM quality_reviews WHERE call_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListQualityReviewsByCall(ctx context.Context, callID uuid.UUID) ([]QualityReview, error) {
	rows, err := q.db.Query(ctx, listQualityReviewsByCall, callID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QualityReview{}
	for rows.Next() {
		var i QualityReview
		if err := rows.Scan(
			&i.ID,
			&i.RecordingID,
			&i.CallID,
			&i.ReviewerID,
			&i.Scores,
			&i.TotalScore,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecordingsByCall = `-- name: ListRecordingsByCall :many
SELECT id, call_id, backend, bucket, object_key, size_bytes, duration_sec, format, created_at, deleted_at FROM recordings WHERE call_id = $1 AND deleted_at IS NULL ORDER BY created_at
`

func (q *Queries) ListRecordingsByCall(ctx context.Context, callID uuid.UUID) ([]Recording, error) {
	rows, err := q.db.Query(ctx, listRecordingsByCall, callID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Recording{}
	for rows.Next() {
		var i Recording
		if err := rows.Scan(
			&i.ID,
			&i.CallID,
			&i.Backend,
			&i.Bucket,
			&i.ObjectKey,
			&i.SizeBytes,
			&i.DurationSec,
			&i.Format,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTranscriptSince = `-- name: ListTranscriptSince :many
SELECT id, call_id, seq, occurred_at, speaker, kind, content, party_id, agent_id, offset_ms, language, source, provider, utterance_id FROM transcripts
WHERE call_id = $1 AND seq > $2
ORDER BY seq
LIMIT $3
`

type ListTranscriptSinceParams struct {
	CallID uuid.UUID `json:"callId"`
	Seq    int32     `json:"seq"`
	Limit  int32     `json:"limit"`
}

// ListTranscriptSince serves the backfill cursor. seq is dense per call, so
// "everything after what I have" is a range scan on uq_transcripts_call_id_seq.
func (q *Queries) ListTranscriptSince(ctx context.Context, arg ListTranscriptSinceParams) ([]Transcript, error) {
	rows, err := q.db.Query(ctx, listTranscriptSince, arg.CallID, arg.Seq, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transcript{}
	for rows.Next() {
		var i Transcript
		if err := rows.Scan(
			&i.ID,
			&i.CallID,
			&i.Seq,
			&i.OccurredAt,
			&i.Speaker,
			&i.Kind,
			&i.Content,
			&i.PartyID,
			&i.AgentID,
			&i.OffsetMs,
			&i.Language,
			&i.Source,
			&i.Provider,
			&i.UtteranceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTranscripts = `-- name: ListTranscripts :many
SELECT id, call_id, seq, occurred_at, speaker, kind, content, party_id, agent_id, offset_ms, language, source, provider, utterance_id FROM transcripts WHERE call_id = $1 ORDER BY seq
`

func (q *Queries) ListTranscripts(ctx context.Context, callID uuid.UUID) ([]Transcript, error) {
	rows, err := q.db.Query(ctx, listTranscripts, callID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transcript{}
	for rows.Next() {
		var i Transcript
		if err := rows.Scan(
			&i.ID,
			&i.CallID,
			&i.Seq,
			&i.OccurredAt,
			&i.Speaker,
			&i.Kind,
			&i.Content,
			&i.PartyID,
			&i.AgentID,
			&i.OffsetMs,
			&i.Language,
			&i.Source,
			&i.Provider,
			&i.UtteranceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWrapUpsForCalls = `-- name: ListWrapUpsForCalls :many
SELECT call_id, agent_id, disposition_code, disposition_label, note, created_at, is_confirmed FROM wrap_ups
WHERE call_id = ANY($1::uuid[])
ORDER BY created_at DESC
`

// ListWrapUpsForCalls reads every wrap-up filed against a page of calls, so a
// ledger listing can attach them without a join whose nullability sqlc would
// have to guess at.
func (q *Queries) ListWrapUpsForCalls(ctx context.Context, callIds []uuid.UUID) ([]WrapUp, error) {
	rows, err := q.db.Query(ctx, listWrapUpsForCalls, callIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WrapUp{}
	for rows.Next() {
		var i WrapUp
		if err := rows.Scan(
			&i.CallID,
			&i.AgentID,
			&i.DispositionCode,
			&i.DispositionLabel,
			&i.Note,
			&i.CreatedAt,
			&i.IsConfirmed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCallbackAttempt = `-- name: MarkCallbackAttempt :one
UPDATE callbacks
SET last_attempt_call_id = $2, last_attempt_at = now(), last_attempt_status = NULL
WHERE id = $1 AND status = 'CLAIMED' AND handled_by = $3
RETURNING id, call_id, queue_id, phone_number, message, status, created_at, handled_by, handled_at, last_attempt_call_id, last_attempt_at, last_attempt_status
`

type MarkCallbackAttemptParams struct {
	ID                uuid.UUID  `json:"id"`
	LastAttemptCallID *uuid.UUID `json:"lastAttemptCallId"`
	HandledBy         *uuid.UUID `json:"handledBy"`
}

func (q *Queries) MarkCallbackAttempt(ctx context.Context, arg MarkCallbackAttemptParams) (Callback, error) {
	row := q.db.QueryRow(ctx, markCallbackAttempt, arg.ID, arg.LastAttemptCallID, arg.HandledBy)
	var i Callback
	err := row.Scan(
		&i.ID,
		&i.CallID,
		&i.QueueID,
		&i.PhoneNumber,
		&i.Message,
		&i.Status,
		&i.CreatedAt,
		&i.HandledBy,
		&i.HandledAt,
		&i.LastAttemptCallID,
		&i.LastAttemptAt,
		&i.LastAttemptStatus,
	)
	return i, err
}

const markRecordingDeleted = `-- name: MarkRecordingDeleted :exec
UPDATE recordings SET deleted_at = now() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) MarkRecordingDeleted(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markRecordingDeleted, id)
	return err
}

const openWrapUp = `-- name: OpenWrapUp :exec
INSERT INTO wrap_ups (call_id, agent_id, disposition_code, disposition_label, note, is_confirmed)
VALUES ($1, $2, $3, $4, '', false)
ON CONFLICT (call_id, agent_id) DO NOTHING
`

type OpenWrapUpParams struct {
	CallID           uuid.UUID `json:"callId"`
	AgentID          uuid.UUID `json:"agentId"`
	DispositionCode  string    `json:"dispositionCode"`
	DispositionLabel string    `json:"dispositionLabel"`
}

// OpenWrapUp starts the record the agent will confirm, with the defaults the
// platform would file on their behalf. Doing it twice for one call is not a
// second record: the first one may already carry what the agent typed.
func (q *Queries) OpenWrapUp(ctx context.Context, arg OpenWrapUpParams) error {
	_, err := q.db.Exec(ctx, openWrapUp,
		arg.CallID,
		arg.AgentID,
		arg.DispositionCode,
		arg.DispositionLabel,
	)
	return err
}

const queueEventsByCall = `-- name: QueueEventsByCall :many
SELECT occurred_at, queue_id, event, agent_id, wait_ms
FROM queue_events
WHERE call_id = $1
ORDER BY occurred_at, id
`

type QueueEventsByCallRow struct {
	OccurredAt pgtype.Timestamptz `json:"occurredAt"`
	QueueID    uuid.UUID          `json:"queueId"`
	Event      string             `json:"event"`
	AgentID    *uuid.UUID         `json:"agentId"`
	WaitMs     int32              `json:"waitMs"`
}

// One call's journey through the queues, oldest first. (occurred_at, id)
// because two movements of one call can share a millisecond and a journey that
// reorders between two reads is not a journey.
func (q *Queries) QueueEventsByCall(ctx context.Context, callID *uuid.UUID) ([]QueueEventsByCallRow, error) {
	rows, err := q.db.Query(ctx, queueEventsByCall, callID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QueueEventsByCallRow{}
	for rows.Next() {
		var i QueueEventsByCallRow
		if err := rows.Scan(
			&i.OccurredAt,
			&i.QueueID,
			&i.Event,
			&i.AgentID,
			&i.WaitMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseCallback = `-- name: ReleaseCallback :one
UPDATE callbacks
SET status = 'OPEN', handled_by = NULL
WHERE id = $1 AND status = 'CLAIMED' AND handled_by = $2
RETURNING id, call_id, queue_id, phone_number, message, status, created_at, handled_by, handled_at, last_attempt_call_id, last_attempt_at, last_attempt_status
`

type ReleaseCallbackParams struct {
	ID        uuid.UUID  `json:"id"`
	HandledBy *uuid.UUID `json:"handledBy"`
}

func (q *Queries) ReleaseCallback(ctx context.Context, arg ReleaseCallbackParams) (Callback, error) {
	row := q.db.QueryRow(ctx, releaseCallback, arg.ID, arg.HandledBy)
	var i Callback
	err := row.Scan(
		&i.ID,
		&i.CallID,
		&i.QueueID,
		&i.PhoneNumber,
		&i.Message,
		&i.Status,
		&i.CreatedAt,
		&i.HandledBy,
		&i.HandledAt,
		&i.LastAttemptCallID,
		&i.LastAttemptAt,
		&i.LastAttemptStatus,
	)
	return i, err
}

const reportAgentToday = `-- name: ReportAgentToday :one
WITH bounds AS (
    SELECT $1::timestamptz AS from_at, $2::timestamptz AS to_at
),
handled AS (
    SELECT count(*)::bigint AS calls_handled,
           COALESCE(sum(talk_sec), 0)::bigint AS talk_sec
    FROM cdrs, bounds
    WHERE primary_agent_id = $3
      AND started_at >= bounds.from_at AND started_at < bounds.to_at
),
intervals AS (
    SELECT l.state, l.reason,
           GREATEST(l.entered_at, bounds.from_at) AS started_at,
           LEAST(COALESCE(l.exited_at, bounds.to_at), bounds.to_at) AS ended_at
    FROM agent_state_logs l, bounds
    WHERE l.agent_id = $3
      AND l.entered_at < bounds.to_at
      AND COALESCE(l.exited_at, bounds.to_at) > bounds.from_at
),
filings AS (
    -- The day's after-call records, counted where they were opened: one per
    -- call the agent finished, and how many of them somebody confirmed.
    SELECT count(*)::bigint AS wrap_ups_opened,
           count(*) FILTER (WHERE is_confirmed)::bigint AS wrap_ups_confirmed
    FROM wrap_ups, bounds
    WHERE agent_id = $3
      AND created_at >= bounds.from_at AND created_at < bounds.to_at
),
presence AS (
    SELECT
        COALESCE(sum(EXTRACT(EPOCH FROM (ended_at - started_at)))
                 FILTER (WHERE reason = 'AFTER_CALL_WORK'), 0)::bigint AS wrap_up_sec,
        count(*) FILTER (WHERE reason = 'AFTER_CALL_WORK')::bigint AS wrap_ups,
        COALESCE(sum(EXTRACT(EPOCH FROM (ended_at - started_at)))
                 FILTER (WHERE state <> 'LOGGED_OUT'), 0)::bigint AS signed_in_sec
    FROM intervals
)
SELECT handled.calls_handled, handled.talk_sec,
       presence.wrap_up_sec, presence.wrap_ups, presence.signed_in_sec,
       filings.wrap_ups_opened, filings.wrap_ups_confirmed
FROM handled, presence, filings
`

type ReportAgentTodayParams struct {
	FromAt  pgtype.Timestamptz `json:"fromAt"`
	ToAt    pgtype.Timestamptz `json:"toAt"`
	AgentID *uuid.UUID         `json:"agentId"`
}

type ReportAgentTodayRow struct {
	CallsHandled     int64 `json:"callsHandled"`
	TalkSec          int64 `json:"talkSec"`
	WrapUpSec        int64 `json:"wrapUpSec"`
	WrapUps          int64 `json:"wrapUps"`
	SignedInSec      int64 `json:"signedInSec"`
	WrapUpsOpened    int64 `json:"wrapUpsOpened"`
	WrapUpsConfirmed int64 `json:"wrapUpsConfirmed"`
}

// ReportAgentToday is one agent's own day.
//
// Two sources, because no single one knows it all: the ledger says what the
// agent handled and for how long they talked, and the presence history says
// how long they were signed in and how much of it went on after-call work.
// Intervals are clipped to the window, and an interval still open — the shift
// they are in, the wrap-up they are typing — counts up to its end.
func (q *Queries) ReportAgentToday(ctx context.Context, arg ReportAgentTodayParams) (ReportAgentTodayRow, error) {
	row := q.db.QueryRow(ctx, reportAgentToday, arg.FromAt, arg.ToAt, arg.AgentID)
	var i ReportAgentTodayRow
	err := row.Scan(
		&i.CallsHandled,
		&i.TalkSec,
		&i.WrapUpSec,
		&i.WrapUps,
		&i.SignedInSec,
		&i.WrapUpsOpened,
		&i.WrapUpsConfirmed,
	)
	return i, err
}

const reportByQueue = `-- name: ReportByQueue :many
SELECT
    queue_id,
    count(*)                                                           AS total_calls,
    count(*) FILTER (WHERE status = 'ANSWERED')                        AS answered_calls,
    count(*) FILTER (WHERE missed_reason IN
        ('SHORT_ABANDONED', 'ABANDONED_RINGING', 'ABANDONED_WAITING')) AS abandoned_calls,
    count(*) FILTER (WHERE queue_wait_sec <= 20 AND status = 'ANSWERED') AS answered_within_sla,
    coalesce(avg(queue_wait_sec), 0)::float8                           AS avg_wait_sec,
    coalesce(max(queue_wait_sec), 0)::int                              AS max_wait_sec,
    coalesce(avg(talk_sec) FILTER (WHERE talk_sec > 0), 0)::float8     AS avg_talk_sec
FROM cdrs
WHERE started_at >= $1 AND started_at < $2 AND queue_id IS NOT NULL
GROUP BY queue_id
ORDER BY total_calls DESC
`

type ReportByQueueParams struct {
	StartedAt   pgtype.Timestamptz `json:"startedAt"`
	StartedAt_2 pgtype.Timestamptz `json:"startedAt2"`
}

type ReportByQueueRow struct {
	QueueID           *uuid.UUID `json:"queueId"`
	TotalCalls        int64      `json:"totalCalls"`
	AnsweredCalls     int64      `json:"answeredCalls"`
	AbandonedCalls    int64      `json:"abandonedCalls"`
	AnsweredWithinSla int64      `json:"answeredWithinSla"`
	AvgWaitSec        float64    `json:"avgWaitSec"`
	MaxWaitSec        int32      `json:"maxWaitSec"`
	AvgTalkSec        float64    `json:"avgTalkSec"`
}

func (q *Queries) ReportByQueue(ctx context.Context, arg ReportByQueueParams) ([]ReportByQueueRow, error) {
	rows, err := q.db.Query(ctx, reportByQueue, arg.StartedAt, arg.StartedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportByQueueRow{}
	for rows.Next() {
		var i ReportByQueueRow
		if err := rows.Scan(
			&i.QueueID,
			&i.TotalCalls,
			&i.AnsweredCalls,
			&i.AbandonedCalls,
			&i.AnsweredWithinSla,
			&i.AvgWaitSec,
			&i.MaxWaitSec,
			&i.AvgTalkSec,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportDaily = `-- name: ReportDaily :many
SELECT
    date_trunc('day', started_at)::date                               AS day,
    count(*)                                                          AS total_calls,
    count(*) FILTER (WHERE status = 'ANSWERED')                       AS answered_calls,
    count(*) FILTER (WHERE is_contained)                              AS contained_calls,
    count(*) FILTER (WHERE missed_reason IN
        ('SHORT_ABANDONED', 'ABANDONED_RINGING', 'ABANDONED_WAITING')) AS abandoned_calls
FROM cdrs
WHERE started_at >= $1 AND started_at < $2
GROUP BY 1
ORDER BY 1
`

type ReportDailyParams struct {
	StartedAt   pgtype.Timestamptz `json:"startedAt"`
	StartedAt_2 pgtype.Timestamptz `json:"startedAt2"`
}

type ReportDailyRow struct {
	Day            pgtype.Date `json:"day"`
	TotalCalls     int64       `json:"totalCalls"`
	AnsweredCalls  int64       `json:"answeredCalls"`
	ContainedCalls int64       `json:"containedCalls"`
	AbandonedCalls int64       `json:"abandonedCalls"`
}

func (q *Queries) ReportDaily(ctx context.Context, arg ReportDailyParams) ([]ReportDailyRow, error) {
	rows, err := q.db.Query(ctx, reportDaily, arg.StartedAt, arg.StartedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportDailyRow{}
	for rows.Next() {
		var i ReportDailyRow
		if err := rows.Scan(
			&i.Day,
			&i.TotalCalls,
			&i.AnsweredCalls,
			&i.ContainedCalls,
			&i.AbandonedCalls,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportOverview = `-- name: ReportOverview :one
SELECT
    count(*)                                                          AS total_calls,
    count(*) FILTER (WHERE status = 'ANSWERED')                       AS answered_calls,
    count(*) FILTER (WHERE missed_reason IN
        ('SHORT_ABANDONED', 'ABANDONED_RINGING', 'ABANDONED_WAITING')) AS abandoned_calls,
    count(*) FILTER (WHERE is_contained)                              AS contained_calls,
    count(*) FILTER (WHERE queue_wait_sec <= 20 AND status = 'ANSWERED'
                     AND queue_id IS NOT NULL)                        AS answered_within_sla,
    count(*) FILTER (WHERE queue_id IS NOT NULL)                      AS queue_calls,
    coalesce(avg(queue_wait_sec) FILTER (WHERE queue_id IS NOT NULL), 0)::float8 AS avg_wait_sec,
    coalesce(avg(talk_sec) FILTER (WHERE talk_sec > 0), 0)::float8    AS avg_talk_sec,
    coalesce(avg(bot_sec)  FILTER (WHERE bot_sec  > 0), 0)::float8    AS avg_bot_sec
FROM cdrs
WHERE started_at >= $1 AND started_at < $2
  AND ($3::uuid IS NULL OR queue_id = $3)
`

type ReportOverviewParams struct {
	StartedAt   pgtype.Timestamptz `json:"startedAt"`
	StartedAt_2 pgtype.Timestamptz `json:"startedAt2"`
	QueueID     *uuid.UUID         `json:"queueId"`
}

type ReportOverviewRow struct {
	TotalCalls        int64   `json:"totalCalls"`
	AnsweredCalls     int64   `json:"answeredCalls"`
	AbandonedCalls    int64   `json:"abandonedCalls"`
	ContainedCalls    int64   `json:"containedCalls"`
	AnsweredWithinSla int64   `json:"answeredWithinSla"`
	QueueCalls        int64   `json:"queueCalls"`
	AvgWaitSec        float64 `json:"avgWaitSec"`
	AvgTalkSec        float64 `json:"avgTalkSec"`
	AvgBotSec         float64 `json:"avgBotSec"`
}

func (q *Queries) ReportOverview(ctx context.Context, arg ReportOverviewParams) (ReportOverviewRow, error) {
	row := q.db.QueryRow(ctx, reportOverview, arg.StartedAt, arg.StartedAt_2, arg.QueueID)
	var i ReportOverviewRow
	err := row.Scan(
		&i.TotalCalls,
		&i.AnsweredCalls,
		&i.AbandonedCalls,
		&i.ContainedCalls,
		&i.AnsweredWithinSla,
		&i.QueueCalls,
		&i.AvgWaitSec,
		&i.AvgTalkSec,
		&i.AvgBotSec,
	)
	return i, err
}

const settleCallbackAttempt = `-- name: SettleCallbackAttempt :many
UPDATE callbacks
SET last_attempt_status = $2, last_attempt_at = $3
WHERE last_attempt_call_id = $1
RETURNING id, call_id, queue_id, phone_number, message, status, created_at, handled_by, handled_at, last_attempt_call_id, last_attempt_at, last_attempt_status
`

type SettleCallbackAttemptParams struct {
	LastAttemptCallID *uuid.UUID         `json:"lastAttemptCallId"`
	LastAttemptStatus *string            `json:"lastAttemptStatus"`
	LastAttemptAt     pgtype.Timestamptz `json:"lastAttemptAt"`
}

func (q *Queries) SettleCallbackAttempt(ctx context.Context, arg SettleCallbackAttemptParams) ([]Callback, error) {
	rows, err := q.db.Query(ctx, settleCallbackAttempt, arg.LastAttemptCallID, arg.LastAttemptStatus, arg.LastAttemptAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Callback{}
	for rows.Next() {
		var i Callback
		if err := rows.Scan(
			&i.ID,
			&i.CallID,
			&i.QueueID,
			&i.PhoneNumber,
			&i.Message,
			&i.Status,
			&i.CreatedAt,
			&i.HandledBy,
			&i.HandledAt,
			&i.LastAttemptCallID,
			&i.LastAttemptAt,
			&i.LastAttemptStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCDRHasRecording = `-- name: UpdateCDRHasRecording :exec
UPDATE cdrs SET has_recording = true WHERE call_id = $1
`

func (q *Queries) UpdateCDRHasRecording(ctx context.Context, callID uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateCDRHasRecording, callID)
	return err
}

const upsertWrapUp = `-- name: UpsertWrapUp :one
INSERT INTO wrap_ups (call_id, agent_id, disposition_code, disposition_label, note, is_confirmed)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (call_id, agent_id) DO UPDATE
SET disposition_code  = excluded.disposition_code,
    disposition_label = excluded.disposition_label,
    note              = excluded.note,
    is_confirmed      = excluded.is_confirmed
RETURNING call_id, agent_id, disposition_code, disposition_label, note, created_at, is_confirmed
`

type UpsertWrapUpParams struct {
	CallID           uuid.UUID `json:"callId"`
	AgentID          uuid.UUID `json:"agentId"`
	DispositionCode  string    `json:"dispositionCode"`
	DispositionLabel string    `json:"dispositionLabel"`
	Note             string    `json:"note"`
	IsConfirmed      bool      `json:"isConfirmed"`
}

// UpsertWrapUp writes the record whole. created_at is left as it was on an
// existing row: it is when after-call work began, not when it was last
// touched, and the day's numbers are grouped by it.
func (q *Queries) UpsertWrapUp(ctx context.Context, arg UpsertWrapUpParams) (WrapUp, error) {
	row := q.db.QueryRow(ctx, upsertWrapUp,
		arg.CallID,
		arg.AgentID,
		arg.DispositionCode,
		arg.DispositionLabel,
		arg.Note,
		arg.IsConfirmed,
	)
	var i WrapUp
	err := row.Scan(
		&i.CallID,
		&i.AgentID,
		&i.DispositionCode,
		&i.DispositionLabel,
		&i.Note,
		&i.CreatedAt,
		&i.IsConfirmed,
	)
	return i, err
}
