// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ledger.sql

package queries

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countCDRs = `-- name: CountCDRs :one
SELECT count(*) FROM cdrs
WHERE ($1::timestamptz IS NULL OR started_at >= $1)
  AND ($2::timestamptz IS NULL OR started_at < $2)
  AND ($3::uuid IS NULL OR queue_id = $3)
  AND ($4::uuid IS NULL OR primary_agent_id = $4
       OR $4 = ANY (agent_ids))
  AND ($5::text = '' OR status = $5)
  AND ($6::text = '' OR did = $6)
  AND ($7::text = '' OR from_number LIKE '%' || $7 || '%')
`

type CountCDRsParams struct {
	FromAt     pgtype.Timestamptz `json:"fromAt"`
	ToAt       pgtype.Timestamptz `json:"toAt"`
	QueueID    *uuid.UUID         `json:"queueId"`
	AgentID    *uuid.UUID         `json:"agentId"`
	Status     string             `json:"status"`
	Did        string             `json:"did"`
	FromNumber string             `json:"fromNumber"`
}

func (q *Queries) CountCDRs(ctx context.Context, arg CountCDRsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCDRs,
		arg.FromAt,
		arg.ToAt,
		arg.QueueID,
		arg.AgentID,
		arg.Status,
		arg.Did,
		arg.FromNumber,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCDR = `-- name: GetCDR :one
SELECT call_id, started_at, answered_at, ended_at, call_type, language, from_number, to_number, did, flow_id, queue_id, agent_ids, primary_agent_id, ring_sec, bot_sec, queue_wait_sec, talk_sec, total_sec, status, hangup_cause, missed_reason, disposition, is_contained, has_recording, user_data, tech, legs FROM cdrs WHERE call_id = $1
`

func (q *Queries) GetCDR(ctx context.Context, callID uuid.UUID) (Cdr, error) {
	row := q.db.QueryRow(ctx, getCDR, callID)
	var i Cdr
	err := row.Scan(
		&i.CallID,
		&i.StartedAt,
		&i.AnsweredAt,
		&i.EndedAt,
		&i.CallType,
		&i.Language,
		&i.FromNumber,
		&i.ToNumber,
		&i.Did,
		&i.FlowID,
		&i.QueueID,
		&i.AgentIds,
		&i.PrimaryAgentID,
		&i.RingSec,
		&i.BotSec,
		&i.QueueWaitSec,
		&i.TalkSec,
		&i.TotalSec,
		&i.Status,
		&i.HangupCause,
		&i.MissedReason,
		&i.Disposition,
		&i.IsContained,
		&i.HasRecording,
		&i.UserData,
		&i.Tech,
		&i.Legs,
	)
	return i, err
}

const getRecording = `-- name: GetRecording :one
SELECT id, call_id, backend, bucket, object_key, size_bytes, duration_sec, format, created_at, deleted_at FROM recordings WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetRecording(ctx context.Context, id uuid.UUID) (Recording, error) {
	row := q.db.QueryRow(ctx, getRecording, id)
	var i Recording
	err := row.Scan(
		&i.ID,
		&i.CallID,
		&i.Backend,
		&i.Bucket,
		&i.ObjectKey,
		&i.SizeBytes,
		&i.DurationSec,
		&i.Format,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const handleCallback = `-- name: HandleCallback :one
UPDATE callbacks
SET status = $2, handled_by = $3, handled_at = now()
WHERE id = $1
RETURNING id, call_id, queue_id, phone_number, message, status, created_at, handled_by, handled_at
`

type HandleCallbackParams struct {
	ID        uuid.UUID  `json:"id"`
	Status    string     `json:"status"`
	HandledBy *uuid.UUID `json:"handledBy"`
}

func (q *Queries) HandleCallback(ctx context.Context, arg HandleCallbackParams) (Callback, error) {
	row := q.db.QueryRow(ctx, handleCallback, arg.ID, arg.Status, arg.HandledBy)
	var i Callback
	err := row.Scan(
		&i.ID,
		&i.CallID,
		&i.QueueID,
		&i.PhoneNumber,
		&i.Message,
		&i.Status,
		&i.CreatedAt,
		&i.HandledBy,
		&i.HandledAt,
	)
	return i, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_logs (actor_id, action, target_kind, target_id, detail, ip)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertAuditLogParams struct {
	ActorID    *uuid.UUID  `json:"actorId"`
	Action     string      `json:"action"`
	TargetKind string      `json:"targetKind"`
	TargetID   string      `json:"targetId"`
	Detail     []byte      `json:"detail"`
	IP         *netip.Addr `json:"ip"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.ActorID,
		arg.Action,
		arg.TargetKind,
		arg.TargetID,
		arg.Detail,
		arg.IP,
	)
	return err
}

const insertCDR = `-- name: InsertCDR :exec

INSERT INTO cdrs (
    call_id, started_at, answered_at, ended_at, call_type, language,
    from_number, to_number, did, flow_id, queue_id,
    agent_ids, primary_agent_id,
    ring_sec, bot_sec, queue_wait_sec, talk_sec, total_sec,
    status, hangup_cause, missed_reason, disposition,
    is_contained, has_recording, user_data, tech, legs
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11,
    $12, $13,
    $14, $15, $16, $17, $18,
    $19, $20, $21, $22,
    $23, $24, $25, $26, $27
) ON CONFLICT (call_id) DO NOTHING
`

type InsertCDRParams struct {
	CallID         uuid.UUID          `json:"callId"`
	StartedAt      pgtype.Timestamptz `json:"startedAt"`
	AnsweredAt     pgtype.Timestamptz `json:"answeredAt"`
	EndedAt        pgtype.Timestamptz `json:"endedAt"`
	CallType       string             `json:"callType"`
	Language       string             `json:"language"`
	FromNumber     string             `json:"fromNumber"`
	ToNumber       string             `json:"toNumber"`
	Did            string             `json:"did"`
	FlowID         *uuid.UUID         `json:"flowId"`
	QueueID        *uuid.UUID         `json:"queueId"`
	AgentIds       []uuid.UUID        `json:"agentIds"`
	PrimaryAgentID *uuid.UUID         `json:"primaryAgentId"`
	RingSec        int32              `json:"ringSec"`
	BotSec         int32              `json:"botSec"`
	QueueWaitSec   int32              `json:"queueWaitSec"`
	TalkSec        int32              `json:"talkSec"`
	TotalSec       int32              `json:"totalSec"`
	Status         string             `json:"status"`
	HangupCause    string             `json:"hangupCause"`
	MissedReason   *string            `json:"missedReason"`
	Disposition    string             `json:"disposition"`
	IsContained    bool               `json:"isContained"`
	HasRecording   bool               `json:"hasRecording"`
	UserData       []byte             `json:"userData"`
	Tech           []byte             `json:"tech"`
	Legs           []byte             `json:"legs"`
}

// SPDX-License-Identifier: Apache-2.0
func (q *Queries) InsertCDR(ctx context.Context, arg InsertCDRParams) error {
	_, err := q.db.Exec(ctx, insertCDR,
		arg.CallID,
		arg.StartedAt,
		arg.AnsweredAt,
		arg.EndedAt,
		arg.CallType,
		arg.Language,
		arg.FromNumber,
		arg.ToNumber,
		arg.Did,
		arg.FlowID,
		arg.QueueID,
		arg.AgentIds,
		arg.PrimaryAgentID,
		arg.RingSec,
		arg.BotSec,
		arg.QueueWaitSec,
		arg.TalkSec,
		arg.TotalSec,
		arg.Status,
		arg.HangupCause,
		arg.MissedReason,
		arg.Disposition,
		arg.IsContained,
		arg.HasRecording,
		arg.UserData,
		arg.Tech,
		arg.Legs,
	)
	return err
}

const insertCallback = `-- name: InsertCallback :one
INSERT INTO callbacks (id, call_id, queue_id, phone_number, message)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, call_id, queue_id, phone_number, message, status, created_at, handled_by, handled_at
`

type InsertCallbackParams struct {
	ID          uuid.UUID  `json:"id"`
	CallID      *uuid.UUID `json:"callId"`
	QueueID     *uuid.UUID `json:"queueId"`
	PhoneNumber string     `json:"phoneNumber"`
	Message     string     `json:"message"`
}

func (q *Queries) InsertCallback(ctx context.Context, arg InsertCallbackParams) (Callback, error) {
	row := q.db.QueryRow(ctx, insertCallback,
		arg.ID,
		arg.CallID,
		arg.QueueID,
		arg.PhoneNumber,
		arg.Message,
	)
	var i Callback
	err := row.Scan(
		&i.ID,
		&i.CallID,
		&i.QueueID,
		&i.PhoneNumber,
		&i.Message,
		&i.Status,
		&i.CreatedAt,
		&i.HandledBy,
		&i.HandledAt,
	)
	return i, err
}

const insertQueueEvent = `-- name: InsertQueueEvent :exec
INSERT INTO queue_events (occurred_at, call_id, queue_id, event, agent_id, wait_ms)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertQueueEventParams struct {
	OccurredAt pgtype.Timestamptz `json:"occurredAt"`
	CallID     *uuid.UUID         `json:"callId"`
	QueueID    uuid.UUID          `json:"queueId"`
	Event      string             `json:"event"`
	AgentID    *uuid.UUID         `json:"agentId"`
	WaitMs     int32              `json:"waitMs"`
}

func (q *Queries) InsertQueueEvent(ctx context.Context, arg InsertQueueEventParams) error {
	_, err := q.db.Exec(ctx, insertQueueEvent,
		arg.OccurredAt,
		arg.CallID,
		arg.QueueID,
		arg.Event,
		arg.AgentID,
		arg.WaitMs,
	)
	return err
}

const insertRecording = `-- name: InsertRecording :one
INSERT INTO recordings (id, call_id, backend, bucket, object_key, size_bytes, duration_sec, format)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, call_id, backend, bucket, object_key, size_bytes, duration_sec, format, created_at, deleted_at
`

type InsertRecordingParams struct {
	ID          uuid.UUID `json:"id"`
	CallID      uuid.UUID `json:"callId"`
	Backend     string    `json:"backend"`
	Bucket      string    `json:"bucket"`
	ObjectKey   string    `json:"objectKey"`
	SizeBytes   int64     `json:"sizeBytes"`
	DurationSec int32     `json:"durationSec"`
	Format      string    `json:"format"`
}

func (q *Queries) InsertRecording(ctx context.Context, arg InsertRecordingParams) (Recording, error) {
	row := q.db.QueryRow(ctx, insertRecording,
		arg.ID,
		arg.CallID,
		arg.Backend,
		arg.Bucket,
		arg.ObjectKey,
		arg.SizeBytes,
		arg.DurationSec,
		arg.Format,
	)
	var i Recording
	err := row.Scan(
		&i.ID,
		&i.CallID,
		&i.Backend,
		&i.Bucket,
		&i.ObjectKey,
		&i.SizeBytes,
		&i.DurationSec,
		&i.Format,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

type InsertTranscriptParams struct {
	CallID     uuid.UUID          `json:"callId"`
	Seq        int32              `json:"seq"`
	OccurredAt pgtype.Timestamptz `json:"occurredAt"`
	Role       string             `json:"role"`
	Kind       string             `json:"kind"`
	Content    []byte             `json:"content"`
}

const listCDRs = `-- name: ListCDRs :many
SELECT call_id, started_at, answered_at, ended_at, call_type, language, from_number, to_number, did, flow_id, queue_id, agent_ids, primary_agent_id, ring_sec, bot_sec, queue_wait_sec, talk_sec, total_sec, status, hangup_cause, missed_reason, disposition, is_contained, has_recording, user_data, tech, legs FROM cdrs
WHERE ($1::timestamptz IS NULL OR started_at >= $1)
  AND ($2::timestamptz IS NULL OR started_at < $2)
  AND ($3::uuid IS NULL OR queue_id = $3)
  AND ($4::uuid IS NULL OR primary_agent_id = $4
       OR $4 = ANY (agent_ids))
  AND ($5::text = '' OR status = $5)
  AND ($6::text = '' OR did = $6)
  AND ($7::text = '' OR from_number LIKE '%' || $7 || '%')
ORDER BY started_at DESC
LIMIT $9 OFFSET $8
`

type ListCDRsParams struct {
	FromAt     pgtype.Timestamptz `json:"fromAt"`
	ToAt       pgtype.Timestamptz `json:"toAt"`
	QueueID    *uuid.UUID         `json:"queueId"`
	AgentID    *uuid.UUID         `json:"agentId"`
	Status     string             `json:"status"`
	Did        string             `json:"did"`
	FromNumber string             `json:"fromNumber"`
	PageOffset int32              `json:"pageOffset"`
	PageLimit  int32              `json:"pageLimit"`
}

func (q *Queries) ListCDRs(ctx context.Context, arg ListCDRsParams) ([]Cdr, error) {
	rows, err := q.db.Query(ctx, listCDRs,
		arg.FromAt,
		arg.ToAt,
		arg.QueueID,
		arg.AgentID,
		arg.Status,
		arg.Did,
		arg.FromNumber,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Cdr{}
	for rows.Next() {
		var i Cdr
		if err := rows.Scan(
			&i.CallID,
			&i.StartedAt,
			&i.AnsweredAt,
			&i.EndedAt,
			&i.CallType,
			&i.Language,
			&i.FromNumber,
			&i.ToNumber,
			&i.Did,
			&i.FlowID,
			&i.QueueID,
			&i.AgentIds,
			&i.PrimaryAgentID,
			&i.RingSec,
			&i.BotSec,
			&i.QueueWaitSec,
			&i.TalkSec,
			&i.TotalSec,
			&i.Status,
			&i.HangupCause,
			&i.MissedReason,
			&i.Disposition,
			&i.IsContained,
			&i.HasRecording,
			&i.UserData,
			&i.Tech,
			&i.Legs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCallbacks = `-- name: ListCallbacks :many
SELECT id, call_id, queue_id, phone_number, message, status, created_at, handled_by, handled_at FROM callbacks
WHERE ($1::text = '' OR status = $1)
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListCallbacksParams struct {
	Status     string `json:"status"`
	PageOffset int32  `json:"pageOffset"`
	PageLimit  int32  `json:"pageLimit"`
}

func (q *Queries) ListCallbacks(ctx context.Context, arg ListCallbacksParams) ([]Callback, error) {
	rows, err := q.db.Query(ctx, listCallbacks, arg.Status, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Callback{}
	for rows.Next() {
		var i Callback
		if err := rows.Scan(
			&i.ID,
			&i.CallID,
			&i.QueueID,
			&i.PhoneNumber,
			&i.Message,
			&i.Status,
			&i.CreatedAt,
			&i.HandledBy,
			&i.HandledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecordingsByCall = `-- name: ListRecordingsByCall :many
SELECT id, call_id, backend, bucket, object_key, size_bytes, duration_sec, format, created_at, deleted_at FROM recordings WHERE call_id = $1 AND deleted_at IS NULL ORDER BY created_at
`

func (q *Queries) ListRecordingsByCall(ctx context.Context, callID uuid.UUID) ([]Recording, error) {
	rows, err := q.db.Query(ctx, listRecordingsByCall, callID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Recording{}
	for rows.Next() {
		var i Recording
		if err := rows.Scan(
			&i.ID,
			&i.CallID,
			&i.Backend,
			&i.Bucket,
			&i.ObjectKey,
			&i.SizeBytes,
			&i.DurationSec,
			&i.Format,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTranscripts = `-- name: ListTranscripts :many
SELECT id, call_id, seq, occurred_at, role, kind, content FROM transcripts WHERE call_id = $1 ORDER BY seq
`

func (q *Queries) ListTranscripts(ctx context.Context, callID uuid.UUID) ([]Transcript, error) {
	rows, err := q.db.Query(ctx, listTranscripts, callID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transcript{}
	for rows.Next() {
		var i Transcript
		if err := rows.Scan(
			&i.ID,
			&i.CallID,
			&i.Seq,
			&i.OccurredAt,
			&i.Role,
			&i.Kind,
			&i.Content,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putSetting = `-- name: PutSetting :exec
INSERT INTO settings (key, value) VALUES ($1, $2)
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = now()
`

type PutSettingParams struct {
	Key   string `json:"key"`
	Value []byte `json:"value"`
}

func (q *Queries) PutSetting(ctx context.Context, arg PutSettingParams) error {
	_, err := q.db.Exec(ctx, putSetting, arg.Key, arg.Value)
	return err
}
