// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type SeqBlock struct {
	Name  string `json:"name"`
	Value int64  `json:"value"`
}

type Session struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"userId"`
	TokenHash []byte             `json:"tokenHash"`
	UserAgent *string            `json:"userAgent"`
	IP        *netip.Addr        `json:"ip"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	ExpiresAt pgtype.Timestamptz `json:"expiresAt"`
}

type Setting struct {
	Key       string             `json:"key"`
	Value     []byte             `json:"value"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"passwordHash"`
	DisplayName  string             `json:"displayName"`
	Role         string             `json:"role"`
	Status       string             `json:"status"`
	Locale       *string            `json:"locale"`
	CreatedAt    pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt    pgtype.Timestamptz `json:"updatedAt"`
	LastLoginAt  pgtype.Timestamptz `json:"lastLoginAt"`
}
