// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Agent struct {
	ID                 uuid.UUID          `json:"id"`
	UserID             uuid.UUID          `json:"userId"`
	CallcenterName     string             `json:"callcenterName"`
	WrapUpTimeSec      int32              `json:"wrapUpTimeSec"`
	IsAutoAnswer       bool               `json:"isAutoAnswer"`
	DefaultExtensionID *uuid.UUID         `json:"defaultExtensionId"`
	CreatedAt          pgtype.Timestamptz `json:"createdAt"`
}

type AgentState struct {
	AgentID         uuid.UUID          `json:"agentId"`
	State           string             `json:"state"`
	Reason          *string            `json:"reason"`
	ExtensionNumber *string            `json:"extensionNumber"`
	EnteredAt       pgtype.Timestamptz `json:"enteredAt"`
	WrapUpEndsAt    pgtype.Timestamptz `json:"wrapUpEndsAt"`
	WrapUpCallID    *uuid.UUID         `json:"wrapUpCallId"`
}

type AgentStateLog struct {
	ID        int64              `json:"id"`
	AgentID   uuid.UUID          `json:"agentId"`
	State     string             `json:"state"`
	Reason    *string            `json:"reason"`
	EnteredAt pgtype.Timestamptz `json:"enteredAt"`
	ExitedAt  pgtype.Timestamptz `json:"exitedAt"`
}

type AuditLog struct {
	ID         int64              `json:"id"`
	OccurredAt pgtype.Timestamptz `json:"occurredAt"`
	ActorID    *uuid.UUID         `json:"actorId"`
	Action     string             `json:"action"`
	TargetKind string             `json:"targetKind"`
	TargetID   string             `json:"targetId"`
	Detail     []byte             `json:"detail"`
	IP         *netip.Addr        `json:"ip"`
}

type Callback struct {
	ID          uuid.UUID          `json:"id"`
	CallID      *uuid.UUID         `json:"callId"`
	QueueID     *uuid.UUID         `json:"queueId"`
	PhoneNumber string             `json:"phoneNumber"`
	Message     string             `json:"message"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	HandledBy   *uuid.UUID         `json:"handledBy"`
	HandledAt   pgtype.Timestamptz `json:"handledAt"`
}

type Cdr struct {
	CallID         uuid.UUID          `json:"callId"`
	StartedAt      pgtype.Timestamptz `json:"startedAt"`
	AnsweredAt     pgtype.Timestamptz `json:"answeredAt"`
	EndedAt        pgtype.Timestamptz `json:"endedAt"`
	CallType       string             `json:"callType"`
	Language       string             `json:"language"`
	FromNumber     string             `json:"fromNumber"`
	ToNumber       string             `json:"toNumber"`
	Did            string             `json:"did"`
	FlowID         *uuid.UUID         `json:"flowId"`
	QueueID        *uuid.UUID         `json:"queueId"`
	AgentIds       []uuid.UUID        `json:"agentIds"`
	PrimaryAgentID *uuid.UUID         `json:"primaryAgentId"`
	RingSec        int32              `json:"ringSec"`
	BotSec         int32              `json:"botSec"`
	QueueWaitSec   int32              `json:"queueWaitSec"`
	TalkSec        int32              `json:"talkSec"`
	TotalSec       int32              `json:"totalSec"`
	Status         string             `json:"status"`
	HangupCause    string             `json:"hangupCause"`
	MissedReason   *string            `json:"missedReason"`
	Disposition    string             `json:"disposition"`
	IsContained    bool               `json:"isContained"`
	HasRecording   bool               `json:"hasRecording"`
	UserData       []byte             `json:"userData"`
	Tech           []byte             `json:"tech"`
	Legs           []byte             `json:"legs"`
}

type Contact struct {
	ID          uuid.UUID          `json:"id"`
	PhoneNumber string             `json:"phoneNumber"`
	Name        string             `json:"name"`
	Company     string             `json:"company"`
	Email       string             `json:"email"`
	Tags        []string           `json:"tags"`
	Notes       string             `json:"notes"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
	UpdatedBy   *uuid.UUID         `json:"updatedBy"`
}

type Did struct {
	ID                 uuid.UUID          `json:"id"`
	Number             string             `json:"number"`
	Language           string             `json:"language"`
	FlowID             *uuid.UUID         `json:"flowId"`
	FallbackQueueID    *uuid.UUID         `json:"fallbackQueueId"`
	IsRecordingEnabled bool               `json:"isRecordingEnabled"`
	Description        string             `json:"description"`
	IsEnabled          bool               `json:"isEnabled"`
	CreatedAt          pgtype.Timestamptz `json:"createdAt"`
}

type Disposition struct {
	Code         string `json:"code"`
	CategoryCode string `json:"categoryCode"`
	Label        string `json:"label"`
	Position     int32  `json:"position"`
	IsEnabled    bool   `json:"isEnabled"`
}

type DispositionCategory struct {
	Code     string `json:"code"`
	Label    string `json:"label"`
	Position int32  `json:"position"`
}

type Extension struct {
	ID          uuid.UUID          `json:"id"`
	Number      string             `json:"number"`
	Kind        string             `json:"kind"`
	Password    string             `json:"password"`
	DisplayName string             `json:"displayName"`
	IsEnabled   bool               `json:"isEnabled"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
}

type Flow struct {
	ID                  uuid.UUID          `json:"id"`
	Slug                string             `json:"slug"`
	Name                string             `json:"name"`
	DraftSpec           []byte             `json:"draftSpec"`
	PublishedRevisionID *uuid.UUID         `json:"publishedRevisionId"`
	PublishedAt         pgtype.Timestamptz `json:"publishedAt"`
	CreatedAt           pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt           pgtype.Timestamptz `json:"updatedAt"`
}

type FlowRevision struct {
	ID        uuid.UUID          `json:"id"`
	FlowID    uuid.UUID          `json:"flowId"`
	Spec      []byte             `json:"spec"`
	Note      string             `json:"note"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
}

type LuaccDid struct {
	Number                 string  `json:"number"`
	Language               string  `json:"language"`
	IsRecordingEnabled     bool    `json:"isRecordingEnabled"`
	FallbackQueueExtNumber *string `json:"fallbackQueueExtNumber"`
	IsEnabled              bool    `json:"isEnabled"`
}

type LuaccDirectory struct {
	Number       string `json:"number"`
	Password     string `json:"password"`
	DisplayName  string `json:"displayName"`
	IsEnabled    bool   `json:"isEnabled"`
	IsAutoAnswer bool   `json:"isAutoAnswer"`
}

type LuaccQueue struct {
	Name                     string      `json:"name"`
	ExtNumber                string      `json:"extNumber"`
	Strategy                 string      `json:"strategy"`
	MohSound                 string      `json:"mohSound"`
	MaxWaitSec               int32       `json:"maxWaitSec"`
	MaxWaitNoAgentSec        int32       `json:"maxWaitNoAgentSec"`
	AnnounceSound            *string     `json:"announceSound"`
	AnnounceFrequencySec     int32       `json:"announceFrequencySec"`
	IsTierRulesApplied       interface{} `json:"isTierRulesApplied"`
	TierRuleWaitSec          interface{} `json:"tierRuleWaitSec"`
	DiscardAbandonedAfterSec int32       `json:"discardAbandonedAfterSec"`
	IsAbandonedResumeAllowed bool        `json:"isAbandonedResumeAllowed"`
	IsRecordingEnabled       bool        `json:"isRecordingEnabled"`
	OverflowType             interface{} `json:"overflowType"`
	OverflowTarget           interface{} `json:"overflowTarget"`
	OverflowSound            interface{} `json:"overflowSound"`
	IsEnabled                bool        `json:"isEnabled"`
}

type QualityReview struct {
	ID          uuid.UUID          `json:"id"`
	RecordingID uuid.UUID          `json:"recordingId"`
	CallID      uuid.UUID          `json:"callId"`
	ReviewerID  uuid.UUID          `json:"reviewerId"`
	Scores      []byte             `json:"scores"`
	TotalScore  int16              `json:"totalScore"`
	Notes       string             `json:"notes"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
}

type Queue struct {
	ID                       uuid.UUID          `json:"id"`
	Name                     string             `json:"name"`
	ExtNumber                string             `json:"extNumber"`
	DisplayName              string             `json:"displayName"`
	Strategy                 string             `json:"strategy"`
	MohSound                 string             `json:"mohSound"`
	MaxWaitSec               int32              `json:"maxWaitSec"`
	MaxWaitNoAgentSec        int32              `json:"maxWaitNoAgentSec"`
	AnnounceSound            *string            `json:"announceSound"`
	AnnounceFrequencySec     int32              `json:"announceFrequencySec"`
	TierRules                []byte             `json:"tierRules"`
	DiscardAbandonedAfterSec int32              `json:"discardAbandonedAfterSec"`
	IsAbandonedResumeAllowed bool               `json:"isAbandonedResumeAllowed"`
	RonaDelaySec             int32              `json:"ronaDelaySec"`
	SlaThresholdSec          int32              `json:"slaThresholdSec"`
	IsRecordingEnabled       bool               `json:"isRecordingEnabled"`
	Hours                    []byte             `json:"hours"`
	Overflow                 []byte             `json:"overflow"`
	IsEnabled                bool               `json:"isEnabled"`
	CreatedAt                pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt                pgtype.Timestamptz `json:"updatedAt"`
}

type QueueAgent struct {
	QueueID  uuid.UUID `json:"queueId"`
	AgentID  uuid.UUID `json:"agentId"`
	Level    int32     `json:"level"`
	Position int32     `json:"position"`
}

type QueueEvent struct {
	ID         int64              `json:"id"`
	OccurredAt pgtype.Timestamptz `json:"occurredAt"`
	CallID     *uuid.UUID         `json:"callId"`
	QueueID    uuid.UUID          `json:"queueId"`
	Event      string             `json:"event"`
	AgentID    *uuid.UUID         `json:"agentId"`
	WaitMs     int32              `json:"waitMs"`
}

type Recording struct {
	ID          uuid.UUID          `json:"id"`
	CallID      uuid.UUID          `json:"callId"`
	Backend     string             `json:"backend"`
	Bucket      string             `json:"bucket"`
	ObjectKey   string             `json:"objectKey"`
	SizeBytes   int64              `json:"sizeBytes"`
	DurationSec int32              `json:"durationSec"`
	Format      string             `json:"format"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	DeletedAt   pgtype.Timestamptz `json:"deletedAt"`
}

type SeqBlock struct {
	Name  string `json:"name"`
	Value int64  `json:"value"`
}

type Session struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"userId"`
	TokenHash []byte             `json:"tokenHash"`
	UserAgent *string            `json:"userAgent"`
	IP        *netip.Addr        `json:"ip"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	ExpiresAt pgtype.Timestamptz `json:"expiresAt"`
}

type Setting struct {
	Key       string             `json:"key"`
	Value     []byte             `json:"value"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}

type Transcript struct {
	ID          int64              `json:"id"`
	CallID      uuid.UUID          `json:"callId"`
	Seq         int32              `json:"seq"`
	OccurredAt  pgtype.Timestamptz `json:"occurredAt"`
	Speaker     string             `json:"speaker"`
	Kind        string             `json:"kind"`
	Content     []byte             `json:"content"`
	PartyID     *uuid.UUID         `json:"partyId"`
	AgentID     *uuid.UUID         `json:"agentId"`
	OffsetMs    int32              `json:"offsetMs"`
	Language    string             `json:"language"`
	Source      string             `json:"source"`
	Provider    string             `json:"provider"`
	UtteranceID string             `json:"utteranceId"`
}

type Trunk struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	Direction   string             `json:"direction"`
	MaxChannels int32              `json:"maxChannels"`
	Config      []byte             `json:"config"`
	IsEnabled   bool               `json:"isEnabled"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"passwordHash"`
	DisplayName  string             `json:"displayName"`
	Role         string             `json:"role"`
	Status       string             `json:"status"`
	Locale       *string            `json:"locale"`
	CreatedAt    pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt    pgtype.Timestamptz `json:"updatedAt"`
	LastLoginAt  pgtype.Timestamptz `json:"lastLoginAt"`
}

type WrapUp struct {
	CallID           uuid.UUID          `json:"callId"`
	AgentID          uuid.UUID          `json:"agentId"`
	DispositionCode  string             `json:"dispositionCode"`
	DispositionLabel string             `json:"dispositionLabel"`
	CategoryCode     string             `json:"categoryCode"`
	CategoryLabel    string             `json:"categoryLabel"`
	Note             string             `json:"note"`
	CreatedAt        pgtype.Timestamptz `json:"createdAt"`
}
