// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: seq.sql

package queries

import (
	"context"
)

const reserveSeqBlock = `-- name: ReserveSeqBlock :one

UPDATE seq_blocks
SET value = value + $1::bigint
WHERE name = $2
RETURNING value
`

type ReserveSeqBlockParams struct {
	BlockSize int64  `json:"blockSize"`
	Name      string `json:"name"`
}

// SPDX-License-Identifier: Apache-2.0
func (q *Queries) ReserveSeqBlock(ctx context.Context, arg ReserveSeqBlockParams) (int64, error) {
	row := q.db.QueryRow(ctx, reserveSeqBlock, arg.BlockSize, arg.Name)
	var value int64
	err := row.Scan(&value)
	return value, err
}
