// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package queries

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one

INSERT INTO sessions (id, user_id, token_hash, user_agent, ip, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, token_hash, user_agent, ip, created_at, expires_at
`

type CreateSessionParams struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"userId"`
	TokenHash []byte             `json:"tokenHash"`
	UserAgent *string            `json:"userAgent"`
	IP        *netip.Addr        `json:"ip"`
	ExpiresAt pgtype.Timestamptz `json:"expiresAt"`
}

// SPDX-License-Identifier: Apache-2.0
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.UserAgent,
		arg.IP,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.UserAgent,
		&i.IP,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const deleteSessionsForUser = `-- name: DeleteSessionsForUser :exec
DELETE FROM sessions WHERE user_id = $1
`

func (q *Queries) DeleteSessionsForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSessionsForUser, userID)
	return err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT sessions.id, sessions.user_id, sessions.token_hash, sessions.user_agent, sessions.ip, sessions.created_at, sessions.expires_at, users.id, users.username, users.password_hash, users.display_name, users.role, users.status, users.locale, users.created_at, users.updated_at, users.last_login_at
FROM sessions
JOIN users ON users.id = sessions.user_id
WHERE sessions.token_hash = $1 AND sessions.expires_at > now()
`

type GetSessionByTokenHashRow struct {
	Session Session `json:"session"`
	User    User    `json:"user"`
}

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.Session.ID,
		&i.Session.UserID,
		&i.Session.TokenHash,
		&i.Session.UserAgent,
		&i.Session.IP,
		&i.Session.CreatedAt,
		&i.Session.ExpiresAt,
		&i.User.ID,
		&i.User.Username,
		&i.User.PasswordHash,
		&i.User.DisplayName,
		&i.User.Role,
		&i.User.Status,
		&i.User.Locale,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
		&i.User.LastLoginAt,
	)
	return i, err
}
