// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sipsessions.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExpiredSIPSessions = `-- name: DeleteExpiredSIPSessions :execrows
DELETE FROM sip_sessions WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredSIPSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSIPSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSIPSession = `-- name: DeleteSIPSession :one
DELETE FROM sip_sessions WHERE agent_id = $1 RETURNING extension
`

// Returns the extension the session was for, because revoking it means
// flushing the registration it was holding and that is the number to flush.
func (q *Queries) DeleteSIPSession(ctx context.Context, agentID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, deleteSIPSession, agentID)
	var extension string
	err := row.Scan(&extension)
	return extension, err
}

const getSIPSession = `-- name: GetSIPSession :one
SELECT agent_id, extension, a1_hash, created_at, expires_at FROM sip_sessions WHERE agent_id = $1
`

func (q *Queries) GetSIPSession(ctx context.Context, agentID uuid.UUID) (SipSession, error) {
	row := q.db.QueryRow(ctx, getSIPSession, agentID)
	var i SipSession
	err := row.Scan(
		&i.AgentID,
		&i.Extension,
		&i.A1Hash,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const upsertSIPSession = `-- name: UpsertSIPSession :one

INSERT INTO sip_sessions (agent_id, extension, a1_hash, expires_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (agent_id) DO UPDATE
   SET extension  = EXCLUDED.extension,
       a1_hash    = EXCLUDED.a1_hash,
       created_at = now(),
       expires_at = EXCLUDED.expires_at
RETURNING agent_id, extension, a1_hash, created_at, expires_at
`

type UpsertSIPSessionParams struct {
	AgentID   uuid.UUID          `json:"agentId"`
	Extension string             `json:"extension"`
	A1Hash    string             `json:"a1Hash"`
	ExpiresAt pgtype.Timestamptz `json:"expiresAt"`
}

// SPDX-License-Identifier: Apache-2.0
// One row per agent: issuing a session replaces the previous one, whichever
// extension it was for, so an agent's phone credential has exactly one holder.
func (q *Queries) UpsertSIPSession(ctx context.Context, arg UpsertSIPSessionParams) (SipSession, error) {
	row := q.db.QueryRow(ctx, upsertSIPSession,
		arg.AgentID,
		arg.Extension,
		arg.A1Hash,
		arg.ExpiresAt,
	)
	var i SipSession
	err := row.Scan(
		&i.AgentID,
		&i.Extension,
		&i.A1Hash,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
