// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: telephony.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDID = `-- name: CreateDID :one
INSERT INTO dids (id, number, language, flow_id, fallback_queue_id,
                  is_recording_enabled, description, is_enabled, allow_inbound, allow_outbound, is_default_outbound)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, number, language, flow_id, fallback_queue_id, is_recording_enabled, description, is_enabled, created_at, allow_inbound, allow_outbound, is_default_outbound
`

type CreateDIDParams struct {
	ID                 uuid.UUID  `json:"id"`
	Number             string     `json:"number"`
	Language           string     `json:"language"`
	FlowID             *uuid.UUID `json:"flowId"`
	FallbackQueueID    *uuid.UUID `json:"fallbackQueueId"`
	IsRecordingEnabled bool       `json:"isRecordingEnabled"`
	Description        string     `json:"description"`
	IsEnabled          bool       `json:"isEnabled"`
	AllowInbound       bool       `json:"allowInbound"`
	AllowOutbound      bool       `json:"allowOutbound"`
	IsDefaultOutbound  bool       `json:"isDefaultOutbound"`
}

func (q *Queries) CreateDID(ctx context.Context, arg CreateDIDParams) (Did, error) {
	row := q.db.QueryRow(ctx, createDID,
		arg.ID,
		arg.Number,
		arg.Language,
		arg.FlowID,
		arg.FallbackQueueID,
		arg.IsRecordingEnabled,
		arg.Description,
		arg.IsEnabled,
		arg.AllowInbound,
		arg.AllowOutbound,
		arg.IsDefaultOutbound,
	)
	var i Did
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Language,
		&i.FlowID,
		&i.FallbackQueueID,
		&i.IsRecordingEnabled,
		&i.Description,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.AllowInbound,
		&i.AllowOutbound,
		&i.IsDefaultOutbound,
	)
	return i, err
}

const createExtension = `-- name: CreateExtension :one

INSERT INTO extensions (id, number, password, display_name, is_enabled)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, number, password, display_name, is_enabled, created_at, updated_at
`

type CreateExtensionParams struct {
	ID          uuid.UUID `json:"id"`
	Number      string    `json:"number"`
	Password    string    `json:"password"`
	DisplayName string    `json:"displayName"`
	IsEnabled   bool      `json:"isEnabled"`
}

// SPDX-License-Identifier: Apache-2.0
func (q *Queries) CreateExtension(ctx context.Context, arg CreateExtensionParams) (Extension, error) {
	row := q.db.QueryRow(ctx, createExtension,
		arg.ID,
		arg.Number,
		arg.Password,
		arg.DisplayName,
		arg.IsEnabled,
	)
	var i Extension
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Password,
		&i.DisplayName,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createQueue = `-- name: CreateQueue :one
INSERT INTO queues (
    id, name, ext_number, display_name, strategy, moh_sound,
    max_wait_sec, max_wait_no_agent_sec, announce_sound, announce_frequency_sec,
    tier_rules, discard_abandoned_after_sec, is_abandoned_resume_allowed,
    sla_threshold_sec, is_recording_enabled, hours, overflow, is_enabled
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18
)
RETURNING id, name, ext_number, display_name, strategy, moh_sound, max_wait_sec, max_wait_no_agent_sec, announce_sound, announce_frequency_sec, tier_rules, discard_abandoned_after_sec, is_abandoned_resume_allowed, sla_threshold_sec, is_recording_enabled, hours, overflow, is_enabled, created_at, updated_at
`

type CreateQueueParams struct {
	ID                       uuid.UUID `json:"id"`
	Name                     string    `json:"name"`
	ExtNumber                string    `json:"extNumber"`
	DisplayName              string    `json:"displayName"`
	Strategy                 string    `json:"strategy"`
	MohSound                 string    `json:"mohSound"`
	MaxWaitSec               int32     `json:"maxWaitSec"`
	MaxWaitNoAgentSec        int32     `json:"maxWaitNoAgentSec"`
	AnnounceSound            *string   `json:"announceSound"`
	AnnounceFrequencySec     int32     `json:"announceFrequencySec"`
	TierRules                []byte    `json:"tierRules"`
	DiscardAbandonedAfterSec int32     `json:"discardAbandonedAfterSec"`
	IsAbandonedResumeAllowed bool      `json:"isAbandonedResumeAllowed"`
	SlaThresholdSec          int32     `json:"slaThresholdSec"`
	IsRecordingEnabled       bool      `json:"isRecordingEnabled"`
	Hours                    []byte    `json:"hours"`
	Overflow                 []byte    `json:"overflow"`
	IsEnabled                bool      `json:"isEnabled"`
}

func (q *Queries) CreateQueue(ctx context.Context, arg CreateQueueParams) (Queue, error) {
	row := q.db.QueryRow(ctx, createQueue,
		arg.ID,
		arg.Name,
		arg.ExtNumber,
		arg.DisplayName,
		arg.Strategy,
		arg.MohSound,
		arg.MaxWaitSec,
		arg.MaxWaitNoAgentSec,
		arg.AnnounceSound,
		arg.AnnounceFrequencySec,
		arg.TierRules,
		arg.DiscardAbandonedAfterSec,
		arg.IsAbandonedResumeAllowed,
		arg.SlaThresholdSec,
		arg.IsRecordingEnabled,
		arg.Hours,
		arg.Overflow,
		arg.IsEnabled,
	)
	var i Queue
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ExtNumber,
		&i.DisplayName,
		&i.Strategy,
		&i.MohSound,
		&i.MaxWaitSec,
		&i.MaxWaitNoAgentSec,
		&i.AnnounceSound,
		&i.AnnounceFrequencySec,
		&i.TierRules,
		&i.DiscardAbandonedAfterSec,
		&i.IsAbandonedResumeAllowed,
		&i.SlaThresholdSec,
		&i.IsRecordingEnabled,
		&i.Hours,
		&i.Overflow,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const defaultOutboundDID = `-- name: DefaultOutboundDID :one

SELECT id, number, language, flow_id, fallback_queue_id, is_recording_enabled, description, is_enabled, created_at, allow_inbound, allow_outbound, is_default_outbound FROM dids WHERE is_default_outbound AND is_enabled
`

// The number a call this platform places comes from when nothing names one.
// At most one row can carry the flag (uq_dids_default_outbound), so this asks
// for it rather than picking among candidates.
func (q *Queries) DefaultOutboundDID(ctx context.Context) (Did, error) {
	row := q.db.QueryRow(ctx, defaultOutboundDID)
	var i Did
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Language,
		&i.FlowID,
		&i.FallbackQueueID,
		&i.IsRecordingEnabled,
		&i.Description,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.AllowInbound,
		&i.AllowOutbound,
		&i.IsDefaultOutbound,
	)
	return i, err
}

const deleteDID = `-- name: DeleteDID :execrows
DELETE FROM dids WHERE id = $1
`

func (q *Queries) DeleteDID(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExtension = `-- name: DeleteExtension :execrows
DELETE FROM extensions WHERE id = $1
`

func (q *Queries) DeleteExtension(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExtension, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteQueue = `-- name: DeleteQueue :execrows
DELETE FROM queues WHERE id = $1
`

func (q *Queries) DeleteQueue(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteQueue, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDIDByNumber = `-- name: GetDIDByNumber :one
SELECT id, number, language, flow_id, fallback_queue_id, is_recording_enabled, description, is_enabled, created_at, allow_inbound, allow_outbound, is_default_outbound FROM dids WHERE number = $1
`

func (q *Queries) GetDIDByNumber(ctx context.Context, number string) (Did, error) {
	row := q.db.QueryRow(ctx, getDIDByNumber, number)
	var i Did
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Language,
		&i.FlowID,
		&i.FallbackQueueID,
		&i.IsRecordingEnabled,
		&i.Description,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.AllowInbound,
		&i.AllowOutbound,
		&i.IsDefaultOutbound,
	)
	return i, err
}

const getExtension = `-- name: GetExtension :one
SELECT id, number, password, display_name, is_enabled, created_at, updated_at FROM extensions WHERE id = $1
`

func (q *Queries) GetExtension(ctx context.Context, id uuid.UUID) (Extension, error) {
	row := q.db.QueryRow(ctx, getExtension, id)
	var i Extension
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Password,
		&i.DisplayName,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQueue = `-- name: GetQueue :one
SELECT id, name, ext_number, display_name, strategy, moh_sound, max_wait_sec, max_wait_no_agent_sec, announce_sound, announce_frequency_sec, tier_rules, discard_abandoned_after_sec, is_abandoned_resume_allowed, sla_threshold_sec, is_recording_enabled, hours, overflow, is_enabled, created_at, updated_at FROM queues WHERE id = $1
`

func (q *Queries) GetQueue(ctx context.Context, id uuid.UUID) (Queue, error) {
	row := q.db.QueryRow(ctx, getQueue, id)
	var i Queue
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ExtNumber,
		&i.DisplayName,
		&i.Strategy,
		&i.MohSound,
		&i.MaxWaitSec,
		&i.MaxWaitNoAgentSec,
		&i.AnnounceSound,
		&i.AnnounceFrequencySec,
		&i.TierRules,
		&i.DiscardAbandonedAfterSec,
		&i.IsAbandonedResumeAllowed,
		&i.SlaThresholdSec,
		&i.IsRecordingEnabled,
		&i.Hours,
		&i.Overflow,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDIDs = `-- name: ListDIDs :many
SELECT id, number, language, flow_id, fallback_queue_id, is_recording_enabled, description, is_enabled, created_at, allow_inbound, allow_outbound, is_default_outbound FROM dids ORDER BY number
`

func (q *Queries) ListDIDs(ctx context.Context) ([]Did, error) {
	rows, err := q.db.Query(ctx, listDIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Did{}
	for rows.Next() {
		var i Did
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.Language,
			&i.FlowID,
			&i.FallbackQueueID,
			&i.IsRecordingEnabled,
			&i.Description,
			&i.IsEnabled,
			&i.CreatedAt,
			&i.AllowInbound,
			&i.AllowOutbound,
			&i.IsDefaultOutbound,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExtensions = `-- name: ListExtensions :many
SELECT e.id, e.number, e.password, e.display_name, e.is_enabled, e.created_at, e.updated_at, a.id AS agent_id
FROM extensions e
LEFT JOIN agents a ON a.default_extension_id = e.id
ORDER BY e.number
`

type ListExtensionsRow struct {
	ID          uuid.UUID          `json:"id"`
	Number      string             `json:"number"`
	Password    string             `json:"password"`
	DisplayName string             `json:"displayName"`
	IsEnabled   bool               `json:"isEnabled"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
	AgentID     *uuid.UUID         `json:"agentId"`
}

func (q *Queries) ListExtensions(ctx context.Context) ([]ListExtensionsRow, error) {
	rows, err := q.db.Query(ctx, listExtensions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExtensionsRow{}
	for rows.Next() {
		var i ListExtensionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.Password,
			&i.DisplayName,
			&i.IsEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AgentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQueueAgents = `-- name: ListQueueAgents :many
SELECT qa.queue_id, qa.agent_id, qa.level, qa.position,
       a.callcenter_name, u.display_name
FROM queue_agents qa
JOIN agents a ON a.id = qa.agent_id
JOIN users u ON u.id = a.user_id
WHERE qa.queue_id = $1
ORDER BY qa.level, qa.position
`

type ListQueueAgentsRow struct {
	QueueID        uuid.UUID `json:"queueId"`
	AgentID        uuid.UUID `json:"agentId"`
	Level          int32     `json:"level"`
	Position       int32     `json:"position"`
	CallcenterName string    `json:"callcenterName"`
	DisplayName    string    `json:"displayName"`
}

func (q *Queries) ListQueueAgents(ctx context.Context, queueID uuid.UUID) ([]ListQueueAgentsRow, error) {
	rows, err := q.db.Query(ctx, listQueueAgents, queueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListQueueAgentsRow{}
	for rows.Next() {
		var i ListQueueAgentsRow
		if err := rows.Scan(
			&i.QueueID,
			&i.AgentID,
			&i.Level,
			&i.Position,
			&i.CallcenterName,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQueues = `-- name: ListQueues :many
SELECT id, name, ext_number, display_name, strategy, moh_sound, max_wait_sec, max_wait_no_agent_sec, announce_sound, announce_frequency_sec, tier_rules, discard_abandoned_after_sec, is_abandoned_resume_allowed, sla_threshold_sec, is_recording_enabled, hours, overflow, is_enabled, created_at, updated_at FROM queues ORDER BY name
`

func (q *Queries) ListQueues(ctx context.Context) ([]Queue, error) {
	rows, err := q.db.Query(ctx, listQueues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Queue{}
	for rows.Next() {
		var i Queue
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ExtNumber,
			&i.DisplayName,
			&i.Strategy,
			&i.MohSound,
			&i.MaxWaitSec,
			&i.MaxWaitNoAgentSec,
			&i.AnnounceSound,
			&i.AnnounceFrequencySec,
			&i.TierRules,
			&i.DiscardAbandonedAfterSec,
			&i.IsAbandonedResumeAllowed,
			&i.SlaThresholdSec,
			&i.IsRecordingEnabled,
			&i.Hours,
			&i.Overflow,
			&i.IsEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQueuesForAgent = `-- name: ListQueuesForAgent :many
SELECT q.id, q.name, q.ext_number, q.display_name, q.strategy, q.moh_sound, q.max_wait_sec, q.max_wait_no_agent_sec, q.announce_sound, q.announce_frequency_sec, q.tier_rules, q.discard_abandoned_after_sec, q.is_abandoned_resume_allowed, q.sla_threshold_sec, q.is_recording_enabled, q.hours, q.overflow, q.is_enabled, q.created_at, q.updated_at
FROM queues q
JOIN queue_agents qa ON qa.queue_id = q.id
WHERE qa.agent_id = $1
ORDER BY q.name
`

func (q *Queries) ListQueuesForAgent(ctx context.Context, agentID uuid.UUID) ([]Queue, error) {
	rows, err := q.db.Query(ctx, listQueuesForAgent, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Queue{}
	for rows.Next() {
		var i Queue
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ExtNumber,
			&i.DisplayName,
			&i.Strategy,
			&i.MohSound,
			&i.MaxWaitSec,
			&i.MaxWaitNoAgentSec,
			&i.AnnounceSound,
			&i.AnnounceFrequencySec,
			&i.TierRules,
			&i.DiscardAbandonedAfterSec,
			&i.IsAbandonedResumeAllowed,
			&i.SlaThresholdSec,
			&i.IsRecordingEnabled,
			&i.Hours,
			&i.Overflow,
			&i.IsEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockExtensionPool = `-- name: LockExtensionPool :exec

SELECT pg_advisory_xact_lock($1::bigint)
`

// Serialises allocation against itself. Without it two transactions read the
// same lowest free number and the second one dies on uq_extensions_number:
// the symptom is a failed request, not a duplicate row. Transaction-scoped, so
// it is released by commit or rollback and cannot be leaked.
func (q *Queries) LockExtensionPool(ctx context.Context, lockKey int64) error {
	_, err := q.db.Exec(ctx, lockExtensionPool, lockKey)
	return err
}

const lowestFreeExtensionNumber = `-- name: LowestFreeExtensionNumber :one

SELECT gs.n::text AS number
FROM generate_series($1::int, $2::int) AS gs(n)
WHERE NOT EXISTS (
    SELECT 1 FROM extensions e WHERE e.number = gs.n::text
)
ORDER BY gs.n
LIMIT 1
`

type LowestFreeExtensionNumberParams struct {
	RangeLow  int32 `json:"rangeLow"`
	RangeHigh int32 `json:"rangeHigh"`
}

// The allocator takes the lowest free number in the pool, not MAX+1: a number
// a departing agent gave back is handed out again, and the pool does not drift
// upwards until it runs out of range. Reuse is safe because no history is
// keyed by an extension — every historical row names the agent's uuid, which
// is never reused (verification F12).
//
// generate_series walks only the configured range, so extensions outside it
// (a queue's number, the bot endpoint) are neither returned nor disturbed.
func (q *Queries) LowestFreeExtensionNumber(ctx context.Context, arg LowestFreeExtensionNumberParams) (string, error) {
	row := q.db.QueryRow(ctx, lowestFreeExtensionNumber, arg.RangeLow, arg.RangeHigh)
	var number string
	err := row.Scan(&number)
	return number, err
}

const lowestFreeQueueNumber = `-- name: LowestFreeQueueNumber :one

SELECT gs.n::text AS ext_number
FROM generate_series($1::int, $2::int) AS gs(n)
WHERE NOT EXISTS (
    SELECT 1 FROM queues q WHERE q.ext_number = gs.n::text
)
ORDER BY gs.n
LIMIT 1
`

type LowestFreeQueueNumberParams struct {
	RangeLow  int32 `json:"rangeLow"`
	RangeHigh int32 `json:"rangeHigh"`
}

// The queue pool, allocated exactly like the extension pool and for the same
// reason: whoever adds a queue is asking for a queue, not for 7004. Its numbers
// live on queues, not in extensions — a queue is dialled, never registered as.
func (q *Queries) LowestFreeQueueNumber(ctx context.Context, arg LowestFreeQueueNumberParams) (string, error) {
	row := q.db.QueryRow(ctx, lowestFreeQueueNumber, arg.RangeLow, arg.RangeHigh)
	var ext_number string
	err := row.Scan(&ext_number)
	return ext_number, err
}

const removeQueueAgent = `-- name: RemoveQueueAgent :execrows
DELETE FROM queue_agents WHERE queue_id = $1 AND agent_id = $2
`

type RemoveQueueAgentParams struct {
	QueueID uuid.UUID `json:"queueId"`
	AgentID uuid.UUID `json:"agentId"`
}

func (q *Queries) RemoveQueueAgent(ctx context.Context, arg RemoveQueueAgentParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeQueueAgent, arg.QueueID, arg.AgentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setQueueAgent = `-- name: SetQueueAgent :exec
INSERT INTO queue_agents (queue_id, agent_id, level, position)
VALUES ($1, $2, $3, $4)
ON CONFLICT (queue_id, agent_id)
DO UPDATE SET level = excluded.level, position = excluded.position
`

type SetQueueAgentParams struct {
	QueueID  uuid.UUID `json:"queueId"`
	AgentID  uuid.UUID `json:"agentId"`
	Level    int32     `json:"level"`
	Position int32     `json:"position"`
}

func (q *Queries) SetQueueAgent(ctx context.Context, arg SetQueueAgentParams) error {
	_, err := q.db.Exec(ctx, setQueueAgent,
		arg.QueueID,
		arg.AgentID,
		arg.Level,
		arg.Position,
	)
	return err
}

const updateDID = `-- name: UpdateDID :one
UPDATE dids
SET language = $2, flow_id = $3, fallback_queue_id = $4,
    is_recording_enabled = $5, description = $6, is_enabled = $7,
    allow_inbound = $8, allow_outbound = $9, is_default_outbound = $10
WHERE id = $1
RETURNING id, number, language, flow_id, fallback_queue_id, is_recording_enabled, description, is_enabled, created_at, allow_inbound, allow_outbound, is_default_outbound
`

type UpdateDIDParams struct {
	ID                 uuid.UUID  `json:"id"`
	Language           string     `json:"language"`
	FlowID             *uuid.UUID `json:"flowId"`
	FallbackQueueID    *uuid.UUID `json:"fallbackQueueId"`
	IsRecordingEnabled bool       `json:"isRecordingEnabled"`
	Description        string     `json:"description"`
	IsEnabled          bool       `json:"isEnabled"`
	AllowInbound       bool       `json:"allowInbound"`
	AllowOutbound      bool       `json:"allowOutbound"`
	IsDefaultOutbound  bool       `json:"isDefaultOutbound"`
}

func (q *Queries) UpdateDID(ctx context.Context, arg UpdateDIDParams) (Did, error) {
	row := q.db.QueryRow(ctx, updateDID,
		arg.ID,
		arg.Language,
		arg.FlowID,
		arg.FallbackQueueID,
		arg.IsRecordingEnabled,
		arg.Description,
		arg.IsEnabled,
		arg.AllowInbound,
		arg.AllowOutbound,
		arg.IsDefaultOutbound,
	)
	var i Did
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Language,
		&i.FlowID,
		&i.FallbackQueueID,
		&i.IsRecordingEnabled,
		&i.Description,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.AllowInbound,
		&i.AllowOutbound,
		&i.IsDefaultOutbound,
	)
	return i, err
}

const updateExtension = `-- name: UpdateExtension :one
UPDATE extensions
SET display_name = $2, is_enabled = $3, updated_at = now()
WHERE id = $1
RETURNING id, number, password, display_name, is_enabled, created_at, updated_at
`

type UpdateExtensionParams struct {
	ID          uuid.UUID `json:"id"`
	DisplayName string    `json:"displayName"`
	IsEnabled   bool      `json:"isEnabled"`
}

func (q *Queries) UpdateExtension(ctx context.Context, arg UpdateExtensionParams) (Extension, error) {
	row := q.db.QueryRow(ctx, updateExtension, arg.ID, arg.DisplayName, arg.IsEnabled)
	var i Extension
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Password,
		&i.DisplayName,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateExtensionPassword = `-- name: UpdateExtensionPassword :exec
UPDATE extensions SET password = $2, updated_at = now() WHERE id = $1
`

type UpdateExtensionPasswordParams struct {
	ID       uuid.UUID `json:"id"`
	Password string    `json:"password"`
}

func (q *Queries) UpdateExtensionPassword(ctx context.Context, arg UpdateExtensionPasswordParams) error {
	_, err := q.db.Exec(ctx, updateExtensionPassword, arg.ID, arg.Password)
	return err
}

const updateQueue = `-- name: UpdateQueue :one
UPDATE queues
SET display_name = $2, strategy = $3, moh_sound = $4,
    max_wait_sec = $5, max_wait_no_agent_sec = $6,
    announce_sound = $7, announce_frequency_sec = $8, tier_rules = $9,
    discard_abandoned_after_sec = $10, is_abandoned_resume_allowed = $11,
    sla_threshold_sec = $12, is_recording_enabled = $13,
    hours = $14, overflow = $15, is_enabled = $16, updated_at = now()
WHERE id = $1
RETURNING id, name, ext_number, display_name, strategy, moh_sound, max_wait_sec, max_wait_no_agent_sec, announce_sound, announce_frequency_sec, tier_rules, discard_abandoned_after_sec, is_abandoned_resume_allowed, sla_threshold_sec, is_recording_enabled, hours, overflow, is_enabled, created_at, updated_at
`

type UpdateQueueParams struct {
	ID                       uuid.UUID `json:"id"`
	DisplayName              string    `json:"displayName"`
	Strategy                 string    `json:"strategy"`
	MohSound                 string    `json:"mohSound"`
	MaxWaitSec               int32     `json:"maxWaitSec"`
	MaxWaitNoAgentSec        int32     `json:"maxWaitNoAgentSec"`
	AnnounceSound            *string   `json:"announceSound"`
	AnnounceFrequencySec     int32     `json:"announceFrequencySec"`
	TierRules                []byte    `json:"tierRules"`
	DiscardAbandonedAfterSec int32     `json:"discardAbandonedAfterSec"`
	IsAbandonedResumeAllowed bool      `json:"isAbandonedResumeAllowed"`
	SlaThresholdSec          int32     `json:"slaThresholdSec"`
	IsRecordingEnabled       bool      `json:"isRecordingEnabled"`
	Hours                    []byte    `json:"hours"`
	Overflow                 []byte    `json:"overflow"`
	IsEnabled                bool      `json:"isEnabled"`
}

func (q *Queries) UpdateQueue(ctx context.Context, arg UpdateQueueParams) (Queue, error) {
	row := q.db.QueryRow(ctx, updateQueue,
		arg.ID,
		arg.DisplayName,
		arg.Strategy,
		arg.MohSound,
		arg.MaxWaitSec,
		arg.MaxWaitNoAgentSec,
		arg.AnnounceSound,
		arg.AnnounceFrequencySec,
		arg.TierRules,
		arg.DiscardAbandonedAfterSec,
		arg.IsAbandonedResumeAllowed,
		arg.SlaThresholdSec,
		arg.IsRecordingEnabled,
		arg.Hours,
		arg.Overflow,
		arg.IsEnabled,
	)
	var i Queue
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ExtNumber,
		&i.DisplayName,
		&i.Strategy,
		&i.MohSound,
		&i.MaxWaitSec,
		&i.MaxWaitNoAgentSec,
		&i.AnnounceSound,
		&i.AnnounceFrequencySec,
		&i.TierRules,
		&i.DiscardAbandonedAfterSec,
		&i.IsAbandonedResumeAllowed,
		&i.SlaThresholdSec,
		&i.IsRecordingEnabled,
		&i.Hours,
		&i.Overflow,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
