// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhooks.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimDueWebhookDeliveries = `-- name: ClaimDueWebhookDeliveries :many
UPDATE webhook_deliveries
SET attempt_count = attempt_count + 1,
    next_attempt_at = now() + interval '1 hour'
WHERE delivery_id IN (
    SELECT delivery_id FROM webhook_deliveries
    WHERE status = 'PENDING' AND next_attempt_at <= now()
    ORDER BY next_attempt_at
    LIMIT $1
    FOR UPDATE SKIP LOCKED
)
RETURNING delivery_id, subscription_id, call_id, revision, payload, status, attempt_count, next_attempt_at, last_status_code, last_error, created_at, delivered_at
`

// ClaimDueWebhookDeliveries takes the oldest work that is due. FOR UPDATE SKIP
// LOCKED so more than one worker — or one worker with more than one goroutine
// — never hands the same delivery to a customer twice.
func (q *Queries) ClaimDueWebhookDeliveries(ctx context.Context, limit int32) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, claimDueWebhookDeliveries, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDelivery{}
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.DeliveryID,
			&i.SubscriptionID,
			&i.CallID,
			&i.Revision,
			&i.Payload,
			&i.Status,
			&i.AttemptCount,
			&i.NextAttemptAt,
			&i.LastStatusCode,
			&i.LastError,
			&i.CreatedAt,
			&i.DeliveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteWebhookSubscription = `-- name: DeleteWebhookSubscription :execrows
DELETE FROM webhook_subscriptions WHERE subscription_id = $1
`

func (q *Queries) DeleteWebhookSubscription(ctx context.Context, subscriptionID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWebhookSubscription, subscriptionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const enabledWebhookSubscriptions = `-- name: EnabledWebhookSubscriptions :many
SELECT subscription_id, filter FROM webhook_subscriptions WHERE is_enabled
`

type EnabledWebhookSubscriptionsRow struct {
	SubscriptionID uuid.UUID `json:"subscriptionId"`
	Filter         []byte    `json:"filter"`
}

// EnabledWebhookSubscriptions is what the enqueue consults on every finished
// call, so it asks for exactly what matching needs and nothing else.
func (q *Queries) EnabledWebhookSubscriptions(ctx context.Context) ([]EnabledWebhookSubscriptionsRow, error) {
	rows, err := q.db.Query(ctx, enabledWebhookSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EnabledWebhookSubscriptionsRow{}
	for rows.Next() {
		var i EnabledWebhookSubscriptionsRow
		if err := rows.Scan(&i.SubscriptionID, &i.Filter); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const enqueueWebhookDelivery = `-- name: EnqueueWebhookDelivery :one
INSERT INTO webhook_deliveries (delivery_id, subscription_id, call_id, revision, payload)
VALUES ($1, $2, $3,
        coalesce((SELECT max(revision) + 1 FROM webhook_deliveries
                  WHERE subscription_id = $2 AND call_id = $3), 1),
        $4)
ON CONFLICT (subscription_id, call_id, revision) DO NOTHING
RETURNING delivery_id, subscription_id, call_id, revision, payload, status, attempt_count, next_attempt_at, last_status_code, last_error, created_at, delivered_at
`

type EnqueueWebhookDeliveryParams struct {
	DeliveryID     uuid.UUID `json:"deliveryId"`
	SubscriptionID uuid.UUID `json:"subscriptionId"`
	CallID         uuid.UUID `json:"callId"`
	Payload        []byte    `json:"payload"`
}

// EnqueueWebhookDelivery writes one delivery. The revision is computed from
// what is already there rather than passed in: the caller knows a CDR was
// replaced, not how many times it has been.
//
// ON CONFLICT DO NOTHING guards the one race that matters — two CDR writes
// landing at once would otherwise both compute revision 2.
func (q *Queries) EnqueueWebhookDelivery(ctx context.Context, arg EnqueueWebhookDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, enqueueWebhookDelivery,
		arg.DeliveryID,
		arg.SubscriptionID,
		arg.CallID,
		arg.Payload,
	)
	var i WebhookDelivery
	err := row.Scan(
		&i.DeliveryID,
		&i.SubscriptionID,
		&i.CallID,
		&i.Revision,
		&i.Payload,
		&i.Status,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LastStatusCode,
		&i.LastError,
		&i.CreatedAt,
		&i.DeliveredAt,
	)
	return i, err
}

const getWebhookSubscription = `-- name: GetWebhookSubscription :one
SELECT subscription_id, name, url, filter, auth_token, is_enabled, created_at, updated_at FROM webhook_subscriptions WHERE subscription_id = $1
`

func (q *Queries) GetWebhookSubscription(ctx context.Context, subscriptionID uuid.UUID) (WebhookSubscription, error) {
	row := q.db.QueryRow(ctx, getWebhookSubscription, subscriptionID)
	var i WebhookSubscription
	err := row.Scan(
		&i.SubscriptionID,
		&i.Name,
		&i.URL,
		&i.Filter,
		&i.AuthToken,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertWebhookSubscription = `-- name: InsertWebhookSubscription :one


INSERT INTO webhook_subscriptions (subscription_id, name, url, filter, auth_token, is_enabled)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING subscription_id, name, url, filter, auth_token, is_enabled, created_at, updated_at
`

type InsertWebhookSubscriptionParams struct {
	SubscriptionID uuid.UUID `json:"subscriptionId"`
	Name           string    `json:"name"`
	URL            string    `json:"url"`
	Filter         []byte    `json:"filter"`
	AuthToken      string    `json:"authToken"`
	IsEnabled      bool      `json:"isEnabled"`
}

// SPDX-License-Identifier: Apache-2.0
// Subscriptions are configuration; deliveries are a work queue. The queries
// keep them apart for the same reason the tables do.
func (q *Queries) InsertWebhookSubscription(ctx context.Context, arg InsertWebhookSubscriptionParams) (WebhookSubscription, error) {
	row := q.db.QueryRow(ctx, insertWebhookSubscription,
		arg.SubscriptionID,
		arg.Name,
		arg.URL,
		arg.Filter,
		arg.AuthToken,
		arg.IsEnabled,
	)
	var i WebhookSubscription
	err := row.Scan(
		&i.SubscriptionID,
		&i.Name,
		&i.URL,
		&i.Filter,
		&i.AuthToken,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWebhookDeliveries = `-- name: ListWebhookDeliveries :many
SELECT delivery_id, subscription_id, call_id, revision, payload, status, attempt_count, next_attempt_at, last_status_code, last_error, created_at, delivered_at FROM webhook_deliveries
WHERE subscription_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListWebhookDeliveriesParams struct {
	SubscriptionID uuid.UUID `json:"subscriptionId"`
	Limit          int32     `json:"limit"`
}

func (q *Queries) ListWebhookDeliveries(ctx context.Context, arg ListWebhookDeliveriesParams) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listWebhookDeliveries, arg.SubscriptionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDelivery{}
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.DeliveryID,
			&i.SubscriptionID,
			&i.CallID,
			&i.Revision,
			&i.Payload,
			&i.Status,
			&i.AttemptCount,
			&i.NextAttemptAt,
			&i.LastStatusCode,
			&i.LastError,
			&i.CreatedAt,
			&i.DeliveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookSubscriptions = `-- name: ListWebhookSubscriptions :many
SELECT subscription_id, name, url, filter, auth_token, is_enabled, created_at, updated_at FROM webhook_subscriptions ORDER BY created_at
`

func (q *Queries) ListWebhookSubscriptions(ctx context.Context) ([]WebhookSubscription, error) {
	rows, err := q.db.Query(ctx, listWebhookSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookSubscription{}
	for rows.Next() {
		var i WebhookSubscription
		if err := rows.Scan(
			&i.SubscriptionID,
			&i.Name,
			&i.URL,
			&i.Filter,
			&i.AuthToken,
			&i.IsEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWebhookDelivered = `-- name: MarkWebhookDelivered :exec
UPDATE webhook_deliveries
SET status = 'DELIVERED', delivered_at = now(), last_status_code = $2, last_error = ''
WHERE delivery_id = $1
`

type MarkWebhookDeliveredParams struct {
	DeliveryID     uuid.UUID `json:"deliveryId"`
	LastStatusCode *int32    `json:"lastStatusCode"`
}

func (q *Queries) MarkWebhookDelivered(ctx context.Context, arg MarkWebhookDeliveredParams) error {
	_, err := q.db.Exec(ctx, markWebhookDelivered, arg.DeliveryID, arg.LastStatusCode)
	return err
}

const markWebhookFailed = `-- name: MarkWebhookFailed :exec
UPDATE webhook_deliveries
SET status = 'FAILED', last_status_code = $2, last_error = $3
WHERE delivery_id = $1
`

type MarkWebhookFailedParams struct {
	DeliveryID     uuid.UUID `json:"deliveryId"`
	LastStatusCode *int32    `json:"lastStatusCode"`
	LastError      string    `json:"lastError"`
}

func (q *Queries) MarkWebhookFailed(ctx context.Context, arg MarkWebhookFailedParams) error {
	_, err := q.db.Exec(ctx, markWebhookFailed, arg.DeliveryID, arg.LastStatusCode, arg.LastError)
	return err
}

const replacePendingWebhookDelivery = `-- name: ReplacePendingWebhookDelivery :one
UPDATE webhook_deliveries
SET payload = $3, attempt_count = 0, next_attempt_at = now(), last_error = '', last_status_code = NULL
WHERE subscription_id = $1 AND call_id = $2 AND status = 'PENDING'
RETURNING delivery_id, subscription_id, call_id, revision, payload, status, attempt_count, next_attempt_at, last_status_code, last_error, created_at, delivered_at
`

type ReplacePendingWebhookDeliveryParams struct {
	SubscriptionID uuid.UUID `json:"subscriptionId"`
	CallID         uuid.UUID `json:"callId"`
	Payload        []byte    `json:"payload"`
}

// ReplacePendingWebhookDelivery is the ordinary case for a corrected CDR: the
// delivery has not gone out yet, so the customer never needs to hear about the
// shorter story at all. Returns nothing when there is no pending row, which is
// how the caller learns it must enqueue a correction instead.
func (q *Queries) ReplacePendingWebhookDelivery(ctx context.Context, arg ReplacePendingWebhookDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, replacePendingWebhookDelivery, arg.SubscriptionID, arg.CallID, arg.Payload)
	var i WebhookDelivery
	err := row.Scan(
		&i.DeliveryID,
		&i.SubscriptionID,
		&i.CallID,
		&i.Revision,
		&i.Payload,
		&i.Status,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LastStatusCode,
		&i.LastError,
		&i.CreatedAt,
		&i.DeliveredAt,
	)
	return i, err
}

const rescheduleWebhookDelivery = `-- name: RescheduleWebhookDelivery :exec
UPDATE webhook_deliveries
SET next_attempt_at = $2, last_status_code = $3, last_error = $4
WHERE delivery_id = $1
`

type RescheduleWebhookDeliveryParams struct {
	DeliveryID     uuid.UUID          `json:"deliveryId"`
	NextAttemptAt  pgtype.Timestamptz `json:"nextAttemptAt"`
	LastStatusCode *int32             `json:"lastStatusCode"`
	LastError      string             `json:"lastError"`
}

func (q *Queries) RescheduleWebhookDelivery(ctx context.Context, arg RescheduleWebhookDeliveryParams) error {
	_, err := q.db.Exec(ctx, rescheduleWebhookDelivery,
		arg.DeliveryID,
		arg.NextAttemptAt,
		arg.LastStatusCode,
		arg.LastError,
	)
	return err
}

const sweepWebhookDeliveries = `-- name: SweepWebhookDeliveries :execrows
DELETE FROM webhook_deliveries
WHERE (status = 'DELIVERED' AND created_at < $1)
   OR (status = 'FAILED'    AND created_at < $2)
`

type SweepWebhookDeliveriesParams struct {
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	CreatedAt_2 pgtype.Timestamptz `json:"createdAt2"`
}

// SweepWebhookDeliveries removes settled rows past their own window. PENDING
// is never swept: a delivery still owed is work, not history, and the retry
// schedule is what ends it.
func (q *Queries) SweepWebhookDeliveries(ctx context.Context, arg SweepWebhookDeliveriesParams) (int64, error) {
	result, err := q.db.Exec(ctx, sweepWebhookDeliveries, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateWebhookSubscription = `-- name: UpdateWebhookSubscription :one
UPDATE webhook_subscriptions
SET name = $2, url = $3, filter = $4, is_enabled = $5,
    auth_token = coalesce($6, auth_token),
    updated_at = now()
WHERE subscription_id = $1
RETURNING subscription_id, name, url, filter, auth_token, is_enabled, created_at, updated_at
`

type UpdateWebhookSubscriptionParams struct {
	SubscriptionID uuid.UUID `json:"subscriptionId"`
	Name           string    `json:"name"`
	URL            string    `json:"url"`
	Filter         []byte    `json:"filter"`
	IsEnabled      bool      `json:"isEnabled"`
	AuthToken      *string   `json:"authToken"`
}

// UpdateWebhookSubscription leaves the token alone when none is supplied.
// sqlc.narg gives a nullable parameter: null means "do not touch", an empty
// string means "clear it". A single non-null parameter could not tell those
// apart, and the difference matters — omitting the field in a PUT must not
// silently disarm a subscription's credential.
func (q *Queries) UpdateWebhookSubscription(ctx context.Context, arg UpdateWebhookSubscriptionParams) (WebhookSubscription, error) {
	row := q.db.QueryRow(ctx, updateWebhookSubscription,
		arg.SubscriptionID,
		arg.Name,
		arg.URL,
		arg.Filter,
		arg.IsEnabled,
		arg.AuthToken,
	)
	var i WebhookSubscription
	err := row.Scan(
		&i.SubscriptionID,
		&i.Name,
		&i.URL,
		&i.Filter,
		&i.AuthToken,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const webhookSubscriptionURLAndToken = `-- name: WebhookSubscriptionURLAndToken :one
SELECT url, auth_token FROM webhook_subscriptions WHERE subscription_id = $1
`

type WebhookSubscriptionURLAndTokenRow struct {
	URL       string `json:"url"`
	AuthToken string `json:"authToken"`
}

func (q *Queries) WebhookSubscriptionURLAndToken(ctx context.Context, subscriptionID uuid.UUID) (WebhookSubscriptionURLAndTokenRow, error) {
	row := q.db.QueryRow(ctx, webhookSubscriptionURLAndToken, subscriptionID)
	var i WebhookSubscriptionURLAndTokenRow
	err := row.Scan(&i.URL, &i.AuthToken)
	return i, err
}
